:doctype: 
:numbered:
:toc: left
:toc-title: Содержание
:toclevels: 3
:lang: rus

== USECASES
 
[NOTE]
Работа по занесению контрольных событий осуществляется по рейсу (кроме занесения отклонений, могут быть и  по документам)

---

=== UC1. Фиксация контрольных событий

<<home, К оглавлению>>

[cols="1,2"]
|===
|*Система*
| LST  система привязки заказов к рейсам

|*Основное действующее лицо*
|Оператор СК

|*Цель*
a|Вести трекинг процессов отгрзуки/приёмки товара, на основании возникающих событий

|*Триггер*
|Контрольное событие, возникающее или не возникающее в процессе выполнения процесса в планируемое время.

|*Предварительные условия*
|

|*Результат*
|Фиксация фактического времени наступления события

|*Постусловия*
|

|*Отклонения*
a|  . Отсутствует рейс в системе - необходимо создать рейс 
    . Не верно введенные данные - необходимо иметь возможность редактировать данные (период возможности корректировки д.б. ограничен для оператора) 

|*Допущения*
|Некоторые контрольные точки Оператор может заносить не фактическим временем и датой


|*Бизнес-правила*
a|  .	Возможность введения текущего или прошедшего времени
    .	Ограничение по текущему году и месяцу
    .	Оператор может ввести данные в пределах двух дней


|*Не решенные вопросы*
|

|===


.Основной поток событий. Регистрация фактического времени прибытия ТС под погрузку/разгрузку

[cols=".<1,.^2,>.4", greed=rows, options=header]
|===
|№ Шага
|Действующее лицо
|Описание шага

3+|*Регистрация фактического времени прибытия ТС под погрузку/разгрузку*

|UC 1.1
|Водитель
a|. Водитель обращается оператору, называет ФИО и Маршрут погрузки/разгрузки 
. Ищет рейс по фамилии водителя и маршруту
. Заносит в контрольное поле фактическое время и дату прибытия ТС

3+|*Регистрация фактического времени постановки ТС на ворота под погрузку/разгрузку*

|UC 1.2
|Оператор
a|. Сообщает водителю номер ворот для постановки ТС
. Наступает время погрузки, оператор получает информацию о том, что ТС на ворота встала.
. Заносит в контрольное время и дату постановки ТС на ворота.

3+| *Регистрация фактического времени начала разгрузки/погрузки*

|UC 1.3
|Оператор
a|. Первое тарное место выезжает/заезжает из/в кузова ТС.
. Оператор заносит в контрольное время и дату контрольное событие.

3+|*Регистрация фактического времени окончания погрузки/разгрузки*

|UC 1.4
|Оператор
a|. Последнее тарное место выезжает/заезжает из/в кузова ТС.
. Оператор заносит в контрольное время и дату контрольное событие.

3+a|*Фиксация отклонений*

Отклонения могут возникнуть на любом этапе процесса погрузки/разгрузки


|UC 1.5
|Оператор
a|. Возникло отклонение, оператору сообщили о событии
. Оператор в контрольное поле заносит дату и время начала устранения отклонений.

_Причины отклонений расписываются в процессе фиксации отклонений._

3+a|*Регистрация фактического времени окончания устранения отклонений*

Отклонения могут возникнуть на разных этапах выполнения процесса и относиться к рейсу или отдельному документу.

|UC 1.6
|Оператор
a|. Оператор получает информацию о том, что отклонение устранено
. Оператор в контрольное поле заносит дату и время окончание устранения отклонений.

_Причины отклонений расписываются в процессе фиксации отклонений._

3+|*Регистрация фактического времени готовности груза*

|UC 1.7
|Оператор
a|Оператор получает информацию от склада о готовности груза и фиксирует в контрольном поле эти дату и время (возможен автоматический процесс когда склад отправляет статус по ЗнО «упаковка завершена» или как называет Коновалов Е.А.  `готов к отгрузке` )  

3+|*Регистрация фактического времени начала оформления документов под погрузку*

|UC 1.8
|Оператор
|Оператор получает информацию от ИС (сигнал – способ пока не определен) о том, что можно приступать к оформлению ТСД по рейсу и фиксирует этим подтверждает получение этой информации, после подтверждения в контрольном поле фиксируются дата и время 

3+|*Регистрация фактического времени окончания оформления документов под погрузку*

|UC 1.9
|Оператор
|Оператор заканчивает оформление ТСД по рейсу и фиксирует в контрольном поле дату и время  

3+|*Регистрация фактического времени убытия ТС*

|UC 1.10
|Оператор
a|. Оператор сообщает водителю, что документы готовы и их можно забрать. 
. Водитель приходит, подписывает ТСД и уходит, забирая свои экземпляры. 
. Оператор заносит в контрольное поле фактическое время и дату убытия ТС (это момент когда водитель ушел из операторской с документами)

|===

include::LST UC2.adoc[]

include::LST UC3.adoc[]

include::LST OKRP UC1.adoc[ ]