:numbered:
:toc: top



=== UC 2. Передача признака обобщения

<<home, К оглавлению>>

[cols="1,2"]
|===
|*Система*
| LST  система привязки заказов к рейсам

|*Основное действующее лицо*
|Коммерческая дирекция, специалист УСЛ

|*Цель*
a| . Передать признак "обобщения" при выдаче задания на склад, с условиями обобщения
. Обеспечить единое место управления логистическими признаками.

|*Триггер*
|В момент создания задания ИС

|*Предварительные условия*
| Настроенные правила обобщения

|*Результат*
| Назначение признака обобщения на ЗнО

|*Постусловия*
|

|*Отклонения*
a| . Если вновь появившемся грузополучателям или типам заказов не назначены правила обобщения, выдавать предупреждение и не выгружать в складскую систему

|*Допущения*
a| . Диспетчер склада умеет работать с обобщениями
. Настроены правила назначения признака обобщения


|*Бизнес-правила*
a| . В части собственных отгрузок управлением правил обобщения занимается коммерческая дирекция, 3PL -ОПиКСД. Вводом данных  -ОПиКСД.


|*Не решенные вопросы*
a| * Определиться с местом хранения этого атрибута в 'ERP' или 'OMS'? - *КЕА W22* - ответ от КЕА "во всех ИС"
* Определить порядок назначения признака обобщения *ААА и НЛМ* (управляет справочником ААА монопольно, а НЛМ предоставляет данные ???)
* Список реквизитов которые должны передаваться складу в ЗнО уточнит ААА
* Список критериев правил обобщения предоставит ААА

|===


.Основной поток событий.

[cols=".<1,.^2,>.4", greed=rows, options=header]
|===
|№ Шага
|Действующее лицо
|Описание шага

|UC1
|Администратор рабочей области LST
а|*Настройка правил*

. Появилась потребность настроить правила:
.. Настройка правил по 3PL контрагентам
.. Запрос от  КД по покупателям
.. На основе предупреждений по ненастроенным правилам

. Настраиваем правила обобщения
.. _Список критериев предоставит ААА_
.. Грузополучатель
.. Тип заказа
.. Направление бизнеса
.. По каналу продаж

|UC2
|Администратор рабочей области LST
а|*Назначение признака в ЗнО*

. На вновь созданное ЗнО применяются правила проверки и назначается признак обобщения
.. _Список реквизитов которые должны передаваться складу в ЗнО уточнит ААА_

. ЗнО выгружается в складскую систему


|===


=== UC 3. Фиксация требований договоров к особым условиям 

<<home, К оглавлению>>

[cols="1,2"]
|===
|*Система*
| LST

|*Основное действующее лицо*
|Администратор НСИ

|*Цель*
a| . Хранить управлять в НСИ логистическими признаками, необходимыми для планирования и контроля логистических процессов _(для расчета и предварительных условий в правилах)_
Обеспечить единое место управления логистическими признаками (создания и обогащения).

|*Триггер*
|. Синхронизация мастер-данных из внешних систем для последующего обогащения
. Потребность в создании новых логистических атрибутов

|*Предварительные условия*
| Заведенный параметр в информационную систему

|*Результат*
|Присвоение параметру значения (обновление или создание записи)

|*Постусловия*
|Параметры требующие "историчности", сохраняют (логируют) прежнее состояние

|*Отклонения*
a|

|*Допущения*
|


|*Бизнес-правила*
a| 


|*Не решенные вопросы*
a| .Определить список атрибутов, для учета в требованиях к НСИ

|===


.Основной поток событий.

[cols=".<1,.^2,>.4", greed=rows, options=header]
|===
|№ Шага
|Действующее лицо
|Описание шага

|UC
|
|


|===

=== UC 4. Документ на выполнение внутренних задач склада 

<<home, К оглавлению>>

[cols="1,2"]
|===
|*Система*
| OMS

|*Основное действующее лицо*
|Специалист УСЛ

|*Цель*
a|. Фиксировать потребности поклажедателей, для внутренней обработки товара, для планирования учёта.

|*Триггер*
a|. Потребности от клиента на дополнительную услугу(работу)
. На основании обменов с поклажедателем
. По факту "Акцепта" выдается на склад

|*Предварительные условия*
| . Наличие услуги в НСИ

|*Результат*
| Подтвержденное производственное задание

|*Постусловия*
|

|*Отклонения*
a|

|*Допущения*
|


|*Бизнес-правила*
a|  


|*Не решённые вопросы*
a|* Проанализировать, где производится нормирование по оказываемым услугам? *(Пупышев и Дудаков  - спросить) W21* 
* Решить в какой из ИС будет НСИ.
* В какой из систем будет заноситься заказ на оказание внутренних услуг?

* Существующий список работ по 3PL см в договорах или доп. соглашениях

|===


.Основной поток событий.

[cols=".<1,.^2,>.4", greed=rows, options=header]
|===
|№ Шага
|Действующее лицо
|Описание шага

|UC1
|
|*см UC OKRP UC8 Устранение отклонений (выдача производственных заданий) - Основной поток событий*


|===

=== UC 5.Расписание на разгрузку  

<<home, К оглавлению>>

[cols="1,2"]
|===
|*Система*
| LST

|*Основное действующее лицо*
|Специалист по планированию

|*Цель*
a|. Визуализировать результаты планирования
. Диспетчировать расписание на разгрузку


Нужно заносить в базу ту информацию, которая будет синхронизирована с лог. стандартом и информацией от транспортных логистов, те основные вехи работы с ТС, которые мы занесли и с которой мы будем руководствоваться в дальнейшей работе. Это касается разгрузки и отгрузки.

|*Триггер*
a|. Наступило регламентное время пересмотра графика
. По запросу


|*Предварительные условия*
|Наличие потребности от заказчика

|*Результат*
|Заполненное расписание на разгрузку

|*Постусловия*
|Акцепт изменений
Сохранять предыдущее акцептованное состояние расписания на разгрузку

|*Отклонения*
a|

|*Допущения*
a|. Наличие обмена с TMS по маршрутам


|*Бизнес-правила*
a|. Расписание на разгрузку - это интерфейс с отображением данных соответствующих Логистическому стандарту IN в объёме необходимом для складской деятельности


|*Не решённые вопросы*
a|. Правила акцепта маршрутов полученных обменами из TMS
. *ААА* продумать отклонения

|===


.Основной поток событий.

[cols=".<1,.^2,>.4", greed=rows, options=header]
|===
|№ Шага
|Действующее лицо
|Описание шага

|UC1
|Специалист по планированию
a|*Формирование новой версии плана на разгрузку*

. Фиксация потребности в приёмке от заказчика (если нет в графике на разгрузку)
. Встраиваивание в недельный график (выбор окна, см форму Лог. стандарт вход.xslx) (Смещение, добавление, удаление)
. Сохранить и установить статус "Новый" (Если статус не "Акцептовано", но в расчет не принимается!)

|UC1.1
|Специалист по планированию
a|*Фиксация потребности в приёмке от заказчика*

. Установка атрибутов для последующей группировки
.. Группа поставщиков
.. Подгруппа поставщиков

. При указании поставщика и требуемого объёма ТС, автоматически подставляются параметры:
.. ТМ на ТС (Получаем обменами из LM ?)
.. Линий на ТС (Получаем обменами из LM ?)
.. Нормативное время на разгрузку *(на поставщика)* (НСИ LST  - вычисляемое)
.. Нормативное время на приёмку *(по типу ЗнП)* (НСИ LST  - вычисляемое)

|UC1.2
|Специалист по планированию
a|*Встраиваивание в недельный график*

. Специалист задает и настраивает параметры графика (при необходимости)
.. Количество ТС на одно окно
.. Настройка графика работы

. Планирование доступности окон разгрузки (ограничения наследуются из *UC20*) (заполняем результат планирования в график)
.. Доступность/Не доступность окна
.. Время с которого окно доступно




|UC2
|Специалист по планированию
a|*Согласование плана на разгрузку*

. Распечатать печатную форму плана на разгрузку или отправить по почте для дальнего согласования
. После согласования, изменить статус на "Акцептовано"
. После изменения статуса графика на разгрузку на "Акцептовано", предыдущая версия сохраняется и становится не активной для дальнейшего использования.





|===

// === UC 6 План на вход  Дублирует UC5

// <<home, К оглавлению>>

// [cols="1,2"]
// |===
// |*Система*
// | 

// |*Основное действующее лицо*
// |

// |*Цель*
// a|

// |*Триггер*
// a|

// |*Предварительные условия*
// |

// |*Результат*
// |

// |*Постусловия*
// |

// |*Отклонения*
// a|  

// |*Допущения*
// |


// |*Бизнес-правила*
// a|  


// |*Не решённые вопросы*
// a|

// |===


// .Основной поток событий.

// [cols=".<1,.^2,>.4", greed=rows, options=header]
// |===
// |№ Шага
// |Действующее лицо
// |Описание шага

// |UC
// |
// |


// |===

// === UC 7 План на выход (расписание) Дублирует UC19

// <<home, К оглавлению>>

// [cols="1,2"]
// |===
// |*Система*
// | LST

// |*Основное действующее лицо*
// |Специалист по планированию

// |*Цель*
// a|. Управлять ограничениями по маршрутам
// . Фиксировать договорённости с поклажедателями и поставщиками

// |*Триггер*
// a|. Появляются дополнительные отгрузки (ставится доп. рейс)
// . Задержки или нарушение графика отгрузок
// . Заведение на основании соглашения с поклажедателем

// |*Предварительные условия*
// a|. Наличие маршрута
// . Порядок погрузки (из TMS или сами проставляем) 




// |*Результат*
// |

// |*Постусловия*
// |

// |*Отклонения*
// a|. Маршрут перестал действовать !  - предусмотреть механизм актуализации расписания. *(срок действия)*
// . Ограничения по линиям или тоннажу

// |*Допущения*
// |


// |*Бизнес-правила*
// a|  


// |*Не решённые вопросы*
// a|. _Будет ли TMS передавать порядок погрузки?_


// |===


// .Основной поток событий.

// [cols=".<1,.^2,>.4", greed=rows, options=header]
// |===
// |№ Шага
// |Действующее лицо
// |Описание шага

// |UC
// |
// |


// |===

=== UC 8 SLA 

<<home, К оглавлению>>

[cols="1,2"]
|===
|*Система*
| LST

|*Основное действующее лицо*
|Специалист по планированию

|*Цель*
a|Учет условий SLA, при планировании деятельности склада.

|*Триггер*
a|Согласование SLA

|*Предварительные условия*
|Определить заказчика складских услуг в ИС

|*Результат*
| . Занесение данных SLA в НСИ
. Акцепт SLA

|*Постусловия*
|Акцептование SLA

|*Отклонения*
a| . Период действия SLA заканчивается или просрочен - выводить информационное сообщение пользователю при открытии, плановые показатели рассчитываются по умолчанию
. SLA на Партнёра не настроен  - то плановые показатели рассчитываются по умолчанию

|*Допущения*
|


|*Бизнес-правила*
a|


|*Не решённые вопросы*
a|

|===


.Основной поток событий.

[cols=".<1,.^2,>.4", greed=rows, options=header]
|===
|№ Шага
|Действующее лицо
|Описание шага

|UC1
|Специалист по планированию
a|*Создание документа SLA*

. Создаем документ SLA
. Заполняем необходимые параметры
.. Указываем заказчика складских услуг, при необходимости создаем, настраиваем:
... Заказчик (контрагент)
... Договор (не обязательно  -  в случае собственной операционки)
... Тег для обменов
.. Период действия
.. Устанавливается статус "Новый" (без акцепта, данные настройки в расчет не берутся)
. Выбор и настройка параметров SLA
.. Подбираем тип параметра (пользователь может самостоятельно создавать новые типы в справочнике типов SLA)
.. Указываем значение типа параметра
. Сохраняем документ

|UC2
|Специалист по планированию
a|*Акцепт документа SLA*

. После согласования документа вручную меняем статус на "Акцептовано", данные параметров документа берутся в расчет плановых показателей

|UC3
|Специалист по планированию
a|*Создание документа SLA копированием*

. Создаем документ SLA копированием, создается документ с незаполненными полями период действия
. Статус документа устанавливается "Новый"
. Остальные параметры наследуются из документа-основание

|UC4
|Специалист по планированию
a|*Создание отчета по документам SLA*

Для удобства контроля настроек, необходима функция создания сводного отчета за период или действующие SLA  с группировкой по Заказчику или параметру

|===

=== UC 9 Формирование коммерческих актов

<<home, К оглавлению>>

[cols="1,2"]
|===
|*Система*
| LST

|*Основное действующее лицо*
|Оператор БД, нач. уч. приемки

|*Цель*
a|. Уменьшение трудоемкости, за счет автоматизации заполнения печатной формы коммерческого акта

|*Триггер*
a|. выявленное отклонение - запись на основании рейса в котором выявленному отклонению

|*Предварительные условия*
|

|*Результат*
|Распечатанный и подписанный коммерческий акт, сохраненный в системе документ.

|*Постусловия*
|

|*Отклонения*
a|. Неверно введенные данные/отсутствуют данные  - необходимо иметь возможность редактировать данные 

|*Допущения*
|


|*Бизнес-правила*
a|. Возможность введения текущего времени
. Ограничение по текущему году и месяцу
. Для каждого к/агента существуют собственные печатные формы



|*Не решённые вопросы*
a|. Взять за образец существующий функционал ТАКТЫ (рейсы разгрузка)
Сейчас это работает только для ЛИ  → надо сделать для всех
. (каким документом в ИС фиксируется?)
. *_Уточнить у Смирнова документооборот Ком. актов_*


|===


.Основной поток событий.

[cols=".<1,.^2,>.4", greed=rows, options=header]
|===
|№ Шага
|Действующее лицо
|Описание шага

|UC1
|Оператор
a|*Занесение отклонения в информационную систему*

. Наступило событие подлежащее актированию (склад в процессе разгрузки/приёмки фиксирует повреждение груза), нач. уч. приемки сообщает оператору на какого водителя/рейс  необходимо сделать акт.
. Ищем рейс на который нужно зафиксировать выявленное отклонение
. Вызываем диалоговое окно создания коммерческого акта
.. № коммерческого акта
.. Данные по рейсу и водителю
.. Дата составления
.. Номера ТТН
.. Результат выявленного отклонения


. Оператор открывает диалоговое окно и заносит информацию в необходимые поля (если они не заполнены автоматически).

. Далее сохраняет документ и или отправляет на печать. 



|===

=== UC 10 Комментарии по возникшим отклонениям

<<home, К оглавлению>>

[cols="1,2"]
|===
|*Система*
| LST

|*Основное действующее лицо*
|Оператор БД

|*Цель*
a|. На основании выявленного отклонения внести причину
. Автоматизировать процесс ввода причин на основании выявленных отклонений, уменьшение трудоемкости

|*Триггер*
a| . Выявленное отклонение
. На основании сигнала оператору от ИС о выявленном отклонении

|*Предварительные условия*
|. Настроенные правила классификации причин отклонений
. Настроенные справочник причин отклонений

|*Результат*
|Внесенные данные (отклонение из справочника причин отклонений) в поле рейса "Отметка об отклонении"

|*Постусловия*
|

|*Отклонения*
a|. Неверно введенные данные - необходимо иметь возможность редактировать данные (период возможности корректировки д.б. ограничен для оператора)

|*Допущения*
| Отклонения могут возникнуть на разных этапах выполнения процесса и относиться к рейсу (погрузки/разгрузки) или отдельному документу(погрузки/разгрузки).


|*Бизнес-правила*
a|



|*Не решённые вопросы*
a|. Список отклонений заполняет *ААА*
. На основании списка отклонений, нужно создать правила назначения отклонений, *ААА* 

|===


.Основной поток событий.

[cols=".<1,.^2,>.4", greed=rows, options=header]
|===
|№ Шага
|Действующее лицо
|Описание шага

|UC1
|
a|. Зафиксировано отклонение (вручную или системой) 
. Выбор причины отклонения
.. Автоматизированно на основании применённых правил
.. Вручную из выпадающего списка
. Сохраняем причину

|===

=== UC 11 Товарно-сопроводительные документы и документы перехода права собственности (МХ1-МХ3)

<<home, К оглавлению>>

[cols="1,2"]
|===
|*Система*
| LST

|*Основное действующее лицо*
|Оператор БД

|*Цель*
a|. Иметь возможность оформлять пакет документов по переходу права собственности в процессе отгрузки товара с ответственного хранения
. Оформление ТСД на погрузку/разгрузку

|*Триггер*
a|После подтверждения отгрузки/приёмки

|*Предварительные условия*
|

|*Результат*
a|. Распечатанный пакет документов для *грузополучателя*
. Отправка документа по ЭДО

|*Постусловия*
|

|*Отклонения*
a|. В одном рейсе (ТС) могут быть и ЭДО, и бумажные документы по разным точкам отгрузки.

|*Допущения*
| 


|*Бизнес-правила*
a|. Переход права собственности происходит у нас на складе.



|*Не решённые вопросы*
a|. Сверить порядок действий в диаграммах последовательности по каждому из процессов *ААА*
. Как будет осуществляться процесс смены права собственности??? *РВГ КЕА*

|===


.Основной поток событий.

[cols=".<1,.^2,>.4", greed=rows, options=header]
|===
|№ Шага
|Действующее лицо
|Описание шага

|UC
|
a|



 Найти точку, когда мы можем передать информацию о том что мы подтвердили ЗнО при переходе права собственности
1.	После окончания сборки ЗнО
2.	Описать порядок перехода права собственности (для случая, когда мы покупаем товар с ответственного хранения)
3.	По факту окончания погрузки ТС, оператор должен оформить товарно-сопроводительные документы (+ ТОРГ 13) на эту отгрузку (рейс), предполагается что документы по ЭДО будут уходить автоматически, а бумажные необходимо распечатывать. 
4.	Система информирует оператора БД о том, что можно приступать к оформлению документов (при этом показывает необходимые контрольные данные, типа кол-во ТМ по каждому грузополучателю и пр.) 
5.	Далее оператор нажатием кнопки “печать” инициирует распечатку документов по рейсу на принтер (все настройки стоят в справочниках, печатные формы не выводим) 



Случай снятия с ответственного хранения:

Случай отгрузки собственной продукции:


В блоке LST в части документов товарно-сопроводительные документы - нужно обеспечить контроль выполнения, но не выпуск документов, чтобы снизить нагрузку.
|===

=== UC 12 Запуск приемки в работу

<<home, К оглавлению>>

[cols="1,2"]
|===
|*Система*
| LST

|*Основное действующее лицо*
|Оператор БД

|*Цель*
a|

|*Триггер*
a|

|*Предварительные условия*
|

|*Результат*
|

|*Постусловия*
|

|*Отклонения*
a|При проверке в документе выявлена ошибка (отклонение), оператор его не подтверждает, далее формирует отправку запроса ответственным.

1.	Выбирает проблемный документ
2.	Нажимает кнопку отправить 
3.	Система отправляет письмо с информацией по документу и рейсу на ответственных


|*Допущения*
| 


|*Бизнес-правила*
a|



|*Не решённые вопросы*
a|. *_(ААА какие данные? Только то что перечисленно или еще что то ?)_*

|===


.Основной поток событий.

[cols=".<1,.^2,>.4", greed=rows, options=header]
|===
|№ Шага
|Действующее лицо
|Описание шага

|UC
|
a| .Процесс:
1.	Водитель прибыл на разгрузку
2.	Зарегистрировался у оператора и отдал документы. 
3.	Оператор сверила документы с ИС (суммы документа, номер, дата документа), проверила корректность данных по рейсу (Наличие рейса,  ФИО, перевозчик, ТС) , внесла недостающие данные *_(ААА какие данные? Только то что перечисленно или еще что то ?)_*
4.	Инициирует (акцептовывает рейс)  выгрузку ЗнП в складскую систему. 

|===


=== UC 13 Документы для поклажедателей

<<home, К оглавлению>>

[cols="1,2"]
|===
|*Система*
| LST

|*Основное действующее лицо*
|Оператор БД, ИС, ответственный за устранение инцидентов.

|*Цель*
a|

|*Триггер*
a|

|*Предварительные условия*
|

|*Результат*
|

|*Постусловия*
|

|*Отклонения*
a|


|*Допущения*
| 


|*Бизнес-правила*
a|. Не со всеми поклажедателями обмен документами происходит МХ-1 и МХ-3, по некоторым производится отчет по периоду (СИБУР через отчет раз в месяц). Указываются в договоре. 



|*Не решённые вопросы*
a|. Каким образом будут появляться ЗнО/ЗнП, рейс на погрузку/разгрузку в системе
. Необходимо описать подробно процесс оформления таких документов ААА (с ХРВ обсуждали что от таких схем мы должны отказываться и оформлять МХ в моменте)

|===


.Основной поток событий.

[cols=".<1,.^2,>.4", greed=rows, options=header]
|===
|№ Шага
|Действующее лицо
|Описание шага

|UC
|
a| . Процесс:
1.	Водитель прибыл на разгрузку
2.	Зарегистрировался у оператора и отдал документы. 
3.	Оператор сверила документы с ИС (суммы документа, номер, дата документа), проверила корректность данных по рейсу (Наличие рейса,  ФИО, перевозчик, ТС) , внесла недостающие данные 
4.	Инициирует (акцептовывает рейс)  выгрузку ЗнП в складскую систему. 

|===

=== UC 14 Связывание рейса с ЗнО

<<home, К оглавлению>>

[cols="1,2"]
|===
|*Система*
| LST

|*Основное действующее лицо*
|Оператор БД, ИС ТМС, ИС LST

|*Цель*
a|. Планирование загрузки склада 

|*Триггер*
a|

|*Предварительные условия*
|

|*Результат*
|

|*Постусловия*
|

|*Отклонения*
a|•	Маршрут формирует ТМС (
•	Состав рейса нельзя менять, после начала работы по рейсу (УСЛ / УТЛ)
•	cut off – расписание маршрута (означает старт комплектации)
•	Маршрут – это справочная информация со сценарием исполнения



|*Допущения*
| 


|*Бизнес-правила*
a| ОЧЕРЕДНОЙ рейс - рейс, следующий после текущего, по одному маршруту
ТЕКУЩИЙ рейс – рейс, который на данный момент не отгружен, находится в работе, до точки CutOff




|*Не решённые вопросы*
a|

|===


.Основной поток событий.

[cols=".<1,.^2,>.4", greed=rows, options=header]
|===
|№ Шага
|Действующее лицо
|Описание шага

|UC
|
a| Процесс связывания ЗнО с текущим рейсом:

1.	ЗнО загрузилось в OMS 
2.	Система LST связывает ЗнО с текущим рейсом. Критерии: грузополучатель, направление бизнеса … В каких статусах будут привязываться строки ЗнО?
Процесс пересвязывания ЗнО с текущим рейсом, груз не поместившийся физически в ТС:
1.	Оператор БД дает сигнал о окончании работы с предыдущим рейсом и началом работы с текущим рейсом.
2.	Система производит пересвязывание рейса с очередным Критерии: ….
Процесс связывания ЗнО с текущим рейсом по НСБ:




1.	Из внешней среды (TMS) приходит информация о том, какие грузополучатели, а соответственно и их ЗнО, относятся к этому конкретному рейсу. Эта информация должна поступать до определенного, четко фиксированного времени (есть контрольная временная точка, после которой уже нельзя менять состав рейса по грузополучателям).
2.	На основании поступившей информации (по п.1) ИС определяет ЗнО в соответствующий рейс и инициирует выгрузку на склад (процесс идет онлайн)
3.	При наступлении точки cut off для склада (старт комплектации) ИС перестает добавлять Зно в текущий рейс и добавляет в следующий по дискретности с учетом данных о грузополучателях, которые относятся именно к этому рейсу, поступивших из внешней среды.
4.	Далее, по окончании погрузки и отгрузки ЗнО в рейсе остается факт 

Например, по Маршрут9А (Тверь-Тула-Новомосковск-Ефремов-Орел) есть рейс № 22 на 11.04.20222 и № 23 на 13.04.2022, логистами принято решение что рейс № 22 не будет содержать точку в г. Орел (сумма ЗнО по грузополучателям из этой точки экстремально низкая = 163 р. Или, наоборот, заказов в Орел настолько много что их решено везти отдельным ТС вне дискретности) 


|===


=== UC 15 Подтверждение корректности сверки документов поставки

<<home, К оглавлению>>

[cols="1,2"]
|===
|*Система*
| LST

|*Основное действующее лицо*
|Оператор БД

|*Цель*
a|

|*Триггер*
a|

|*Предварительные условия*
|

|*Результат*
|

|*Постусловия*
|

|*Отклонения*
a|


|*Допущения*
| 


|*Бизнес-правила*
a|



|*Не решённые вопросы*
a|. Сумм по ответственному хранению может не быть
. С чем сверять сумму? Как система проверит с бумагой документы ?

|===


.Основной поток событий.

[cols=".<1,.^2,>.4", greed=rows, options=header]
|===
|№ Шага
|Действующее лицо
|Описание шага

|UC
|
a| Процесс бумажными документами:

1.	Водитель прибыл на разгрузку
2.	Зарегистрировался у оператора и отдал документы. 
3.	Оператор находит в ИС нужный для сверки рейс
4.	Оператор нажимает кнопку проверить документы
5.	Система выбирает все документы по рейсу
6.	Оператор сверила документы с ИС (суммы документа, номер, дата документа), нажимает подтверждение.
7.	Система выпускает рейс в складские системы (в работу)

Процесс документами через ЭДО:

•	Водитель прибыл на разгрузку
•	Зарегистрировался у оператора
•	Оператор находит в ИС нужный для сверки рейс
•	Оператор нажимает кнопку проверить документы
•	Система выбирает все документы по рейсу и автоматизировано проверяет (суммы документа, номер, дата документа)
•	В случае успеха, система оповещает оператора о возможности выгрузки рейса в складскую систему
•	Оператор акцептует рейс
•	Система выпускает рейс в складские системы (в работу)

Отклонения:

1.	Когда по одной накладной 2 ЗнП 
2.	В процессе сверки оператор выявляет отклонение
3.	Выделяет документ с отклонением, поле в котором выявлено отклонение, инициирует отправку запроса ответственным.
4.	Система игнорирует документ при выгрузке рейса в работу на склад.
5.	Оператор ожидает информации устранения отклонения по документам
6.	Оператор находит в ИС нужный для сверки рейс далее, повторяются действия аналогичные процессам ЭДО и бумажные документы


|===

=== UC 16 Оперативная отчетность
<<home, К оглавлению>>

[cols="1,2"]
|===
|*Система*
| LST

|*Основное действующее лицо*
|Оператор БД, специалист по планированию.

|*Цель*
a|

|*Триггер*
a|•	За период
•	По запросу


|*Предварительные условия*
|

|*Результат*
|

|*Постусловия*
|

|*Отклонения*
a|•	В случае не корректно введенных данных, выдается предупреждение.
•	Если нет данных для построения отчётности, выдавать предупреждение о отсутствии данных.



|*Допущения*
| Список отчётности:
Делаются для склада

По фактическому прибытию транспорта - для логистов



|*Бизнес-правила*
a|. Не со всеми поклажедателями обмен документами происходит МХ-1 и МХ-3, по некоторым производится отчет по периоду (СИБУР через отчет раз в месяц). Указываются в договоре. 



|*Не решённые вопросы*
a| ААА Предоставить список оперативной отчетности

|===


.Основной поток событий.

[cols=".<1,.^2,>.4", greed=rows, options=header]
|===
|№ Шага
|Действующее лицо
|Описание шага

|UC
|
a|
•	Поступил запрос или наступило регламентное время формирования отчетности
•	Оператор выбирает необходимые параметры, период, и формирует необходимый отчет
•	Система формирует и выводит отчет
•	Оператор выбирает сохранить отчет или отправить по почте с указанием email 
•	Система сохраняет отчет локально или отправляет адресату с вложением сформированного отчета


|===


=== UC 17 Записи в справочниках
<<home, К оглавлению>>

[cols="1,2"]
|===
|*Система*
| LST

|*Основное действующее лицо*
|1.	Специалист по планированию

|*Цель*
a|

|*Триггер*
a| •	Появилась потребность дополнить или скорректировать существующие данные
•	Оповещение о возникновении новых записей в подчинённых справочниках (справочник-источник находится в другой системе)




|*Предварительные условия*
|

|*Результат*
| Список справочников:

•	Справочник маршрутов
•	
•	
Смотрим справочник и цель его использования


|*Постусловия*
|

|*Отклонения*
a|


|*Допущения*
| 

|*Бизнес-правила*
a|


|*Не решённые вопросы*
a|

|===


.Основной поток событий.

[cols=".<1,.^2,>.4", greed=rows, options=header]
|===
|№ Шага
|Действующее лицо
|Описание шага

|UC
|
|Процесс управления справочниками LST (где мы являемся источником):


Процесс обогащения справочников передаваемых в LST:

Процесс получения справочника маршрутов

1.	Справочник маршрутов получаем из TMS
2.	Вводит специалист по планированию 


|===

=== UC 18 Управление свободными окнами
<<home, К оглавлению>>

[cols="1,2"]
|===
|*Система*
| LST

|*Основное действующее лицо*
| Оператор БД, внутренний/внешний заказчик

|*Цель*
a|. Предоставить возможность коммуницирования и резервирования окна отгрузки/загрузки внешним и внутренним заказчикам

|*Триггер*
a| Поступил запрос от внутреннего/внешнего заказчика (в не графика)




|*Предварительные условия*
|Учитываются окна не зарезервированные в планах Загрузки/Разгрузки
Свободные окна для внеочередных рейсов, Наличие данных по тоннажу ТС, количество строк, количество тарных мест 

|*Результат*
| Резервирование окна под погрузку/разгрузку в оперативном графике управления воротами

|*Постусловия*
| Получение пользователем подтверждения о резерве окна

|*Отклонения*
a|. Машина отменена, необходимо произвести снятие резервов окна (автоматически - API или в ручную)
. Не акцепт резерва окна  - пользователю отправляется сообщение об отмене
. Отсутствие свободных окон - получает сообщение, об отсутствии свободных окон
. Превышение возможности по тоннажу ТС, количеству строк, количество тарных мест - сообщение об невозможности резерва на текущее окно, с предложением ближайшего свободного по искомым параметрам
. Одновременно несколько пользователей пытаются зарезервировать окно - первый, кто начал редактирование - имеет право изменять, остальным выводится сообщение о том,что окно редактируется.


|*Допущения*
| . Возможность получать оперативную информацию об отклонениях из TMS

|*Бизнес-правила*
a|


|*Не решённые вопросы*
a|. Прототип интерфейса (по возможности)
. В графиках загрузки/разгрузки предусмотреть свободные окна с параметрами по рейсу (тоннаж, строки, ...)
. Какие существуют условия для резервирования окна
.. Со стороны грузополучателя
.. Со стороны заказчика
.. Внутренние ограничения

|===


.Основной поток событий.

[cols=".<1,.^2,>.4", greed=rows, options=header]
|===
|№ Шага
|Действующее лицо
|Описание шага

|UC
|
|1.	Поступил запрос от заказчика
2.	Оператор БД, открывает расписание отгрузки/разгрузки, вводит дату на которое должно происходить резервирование.
3.	Система выводит расписание на дату планирования с учетом занятых окон
4.	Оператор ищет свободное окно и нажимает кнопку «Резервировать»
5.	Система через диалог запрашивает выбор рейса
6.	Оператор подтверждает введенные данные
7.	Система создаёт запись в расписании
8.	Оператор информирует заказчика о дате и времени окна

|UC1
|
a|*Выбор свободного окна в оперативном графике управления воротами*

. Система или Оператор, получают информацию обменами либо по почте
. В графике управления воротами выводятся занятые и свободные окна
. Выбираем необходимое окно
. Система выводит диалог получения необходимых параметров для резервирования
. Вводим необходимые параметры
. Производится проверка параметров
. Если проверка прошла, то сообщение об успехе, если нет, то выводится диалог выбора ближайшего свободного окна (по API соответствующие сообщения заказчику)

|UC2
|
a|*Действия после резервирования окна разгрузки*

. Если резервируется окно разгрузки, создается новый рейс
. В новый рейс наследуются плановые данные из резерва

|UC3
|
a|*Действия после резервирования окна загрузки*
_Подумать какие действия нужны_

|UC4
|
a|*Перенос существующего окна на другое время*

. Производится резерв в новом свободном окне
. Снимается резерв с существующего окна
. Заносится плановое время нового свободного окна в атрибут рейса *"Окно для выгрузки по графику для опоздавших ТС"*
. Фиксируется отклонение по рейсу см UC1

|===


=== UC 19 Расписание на отгрузку
<<home, К оглавлению>>

[cols="1,2"]
|===
|*Система*
| LST

|*Основное действующее лицо*
| Специалист по планированию

|*Цель*
a|. Визуализировать результаты планирования
. Диспетчировать расписание на погрузку

|*Триггер*
a|  . Наступило регламентное время пересмотра графика
. По запросу



|*Предварительные условия*
| Наличие потребности от заказчика

|*Результат*
| Заполненное расписание на погрузку

|*Постусловия*
|Акцепт изменений Сохранять предыдущее акцептованное состояние расписания на погрузку

|*Отклонения*
a|


|*Допущения*
a|. Наличие обмена с TMS по маршрутам


|*Бизнес-правила*
a|. Расписание на погрузку - это интерфейс с отображением данных соответствующих Логистическому стандарту OUT в объёме необходимом для складской деятельности


|*Не решённые вопросы*
a|. Правила акцепта маршрутов полученных обменами из TMS
. *ААА* продумать отклонения

|===


.Основной поток событий.

[cols=".<1,.^2,>.4", greed=rows, options=header]
|===
|№ Шага
|Действующее лицо
|Описание шага

|UC1
|Специалист по планированию
a|*Формирование новой версии плана на разгрузку*

. Фиксация потребности в отгрузке от заказчика (если нет в графике на погрузку)
. Встраиваивание в недельный график (выбор окна, см форму Лог. стандарт выход.xslx) (Смещение, добавление, удаление)
. Сохранить и установить статус "Новый" (Если статус не "Акцептовано", но в расчет не принимается!)

|UC1.1
|Специалист по планированию
a|*Фиксация потребности в отгрузке от заказчика*

. Установка атрибутов для последующей группировки
.. Маршрут
... Вручную (где нет собственной доставки, другие заказчики) (самовывоз, курьерская доставка, где мы не управляем заказом транспорта)
... Получаем обменами из TMS
.. Грузополучатели по маршруту (устанавливаются автоматически из маршрута)
.. Направление бизнеса (устанавливаются автоматически из маршрута)

. При указании грузополучателя и требуемого объёма ТС, автоматически подставляются параметры:
.. ТМ на ТС (из WMS)
.. Линий на ТС (из WMS)
.. Средний объём ТС за период (период задаваемый настройками)
.. Средний вес ТС за период (период задаваемый настройками)
.. Нормативное время на погрузку *(на маршрут)* (НСИ LST  - вычисляемое)
.. Нормативное время на комплектацию *(по типу заказа)* (НСИ LST  - вычисляемое)

|UC1.2
|Специалист по планированию
a|*Встраиваивание в недельный график*

. Специалист задает и настраивает параметры графика (при необходимости)
.. Время работы склада (НСИ или настройки)



. Планирование доступности окон разгрузки (ограничения наследуются из *UC20*) (заполняем результат планирования в график)
.. Доступность/Не доступность окна
.. Время с которого окно доступно


|UC2
|Специалист по планированию
a|*Согласование плана на разгрузку*

. Распечатать печатную форму плана на погрузку или отправить по почте для дальнего согласования
. После согласования, изменить статус на "Акцептовано"
. После изменения статуса графика на погрузку на "Акцептовано", предыдущая версия сохраняется и становится не активной для дальнейшего использования.





|===

=== UC 20 План загрузки склада
<<home, К оглавлению>>

[cols="1,2"]
|===
|*Система*
| LST

|*Основное действующее лицо*
| Специалист по планированию

|*Цель*
a|. Оптимизировать нагрузку на склад

|*Триггер*
a|. Анализ ожидаемой и фактической загрузки склада, выявление *проблемных* окон
. Необходимость в корректировке расписания вход/выход (статус документа "Новый")
. Уточненный план *UC21* (Дополнительные рейсы  или фактические отклонения графиков поставки/приёмки)



|*Предварительные условия*

a|. Планируемый/фактический фонд рабочего времени
. Настроенные правила и нормативы (НСИ)
. Ожидаемые/фактически выданные задания
. Перетекающие задания с предыдущего дня, на день планирования (незавершенные задания)

|*Результат*
a| . выдача рекомендаций по наименее загруженным окнам, на основании заданных правил
. План загрузки с заданной дискретностью
. Календарный план загрузки на основании фактических данных

|*Постусловия*
|После акцепта сохранение результатов отчета и применение в расчетах других подсистем

|*Отклонения*
a| Отсутствие внешних данных из ИС - возможность настройки данных "По умолчанию", или ручной корректировки


|*Допущения*
a|. Планирование может выполняться с разными горизонтами, от этого зависит алгоритм расчета, исходные данные

|*Бизнес-правила*
a|


|*Не решённые вопросы*
a|. Необходима модель расчетов в Excel (на этапе проработки пользовательских требований)
. Пример расчета см. *Пример загрузки склада.png*
. Учесть в графике производственные задания

|===


.Основной поток событий.

[cols=".<1,.^2,>.4", greed=rows, options=header]
|===
|№ Шага
|Действующее лицо
|Описание шага

|UC1
|Специалист по планированию 
a|*Формирование базового графика для проведения расчетов*
График строится на основании (дня недели,дня месяца,дня года), продолжительность графика 
настраиваемая (от 24>= _временная шкала планирования_)

. Наполнить график рейсами 
.. Автоматически из справочника маршрутов (на основании настроенной дискретности)
.. Ручное добавление (внеплановые маршруты)
. Заполняются параметры для расчета загрузки склада
. Проверяем на пустые (не заполненные) и не корректные значения, при необходимости корректируем

|UC2
|Специалист по планированию 
a|*Проведение расчетов и корректировка результатов*

. Рассчитываем почасовой график загрузки
. Выводится фактический результат, (шкала времени графика, может увеличиваться в зависимости перехода времени суток)
. Корректировка результатов при необходимости
.. Изменение окна выполнения (промежуток времени)

|UC3
|Специалист по планированию 
a|*Сохранение результатов расчета загрузки склада и акцепт*
. Сохраняем результаты расчета
. Документу присваивается статус "Новый"
. Распечатываем печатную форму или отправляем по почте при необходимости
. Меняем статус на "Акцептовано", при смене статуса данный отчет применяется в других подсистемах см. UC5, 19, 21



|===

=== UC 21 Уточненный план
<<home, К оглавлению>>

[cols="1,2"]
|===
|*Система*
| LST

|*Основное действующее лицо*
| Оператор БД

|*Цель*
a|. Возможность корректировать (изменять) существующие планы

|*Триггер*
a|. Решение о пересмотре существующего плана



|*Предварительные условия*
|Актуальный план для редактирования

|*Результат*
| Сохранение копии плана с одинаковым набором параметров, но разными значениями

|*Постусловия*
|

|*Отклонения*
a|


|*Допущения*
| 

|*Бизнес-правила*
a|


|*Не решённые вопросы*
a|. Аналогия -  в 1С функция создания элемента копированием, когда наследуются все значения.

|===


.Основной поток событий.

[cols=".<1,.^2,>.4", greed=rows, options=header]
|===
|№ Шага
|Действующее лицо
|Описание шага

|UC
|
|

|===

=== UC 22 Расписание выполнения внутренних задач склада
<<home, К оглавлению>>

[cols="1,2"]
|===
|*Система*
| LST

|*Основное действующее лицо*
| Оператор БД

|*Цель*
a|

|*Триггер*
a|  



|*Предварительные условия*
|

|*Результат*
| 

|*Постусловия*
|

|*Отклонения*
a|


|*Допущения*
| 

|*Бизнес-правила*
a|


|*Не решённые вопросы*
a|. По какому признаку группируются
. Прототип расписания

|===


.Основной поток событий.

[cols=".<1,.^2,>.4", greed=rows, options=header]
|===
|№ Шага
|Действующее лицо
|Описание шага

|UC
|
| 1.

|===