@startuml

left to right direction

package OMS as "OMS" {
        artifact ZnO as "ЗнО"
        artifact ZnP as "ЗнП"
        artifact PrZ as "ПрЗ"
        ' artifact corrZnO as "Корректировка ЗнО"

        component StatusDoc as "Назначенеие статусов и атрибутов"
        component suppChain as "Автоматизация создания цепочки поставки"
        component strategySupp as "Стратегия отгрузки"


        ' ZnO --> corrZnO

    }
node TMS
component courier as "Курьерская доставка"

ZnO --> TMS : [Полезные объёмы]
ZnO --> courier: [Полезные объёмы]

@enduml