
@startuml


package nsi as "НСИ" {
        artifact contractor as "Справочник контрагентов"
        artifact logCard as "Справочник маршрутов"

         component contract as "НСИ \n Договора"
        ' Срок рассмотрения претензии

        component AccCode as "НСИ \n Коды приёмки"
    }


@enduml