site:
  title: Antora Demo Site
  # the 404 page and sitemap files only get generated when the url property is set
  url: https://10.2.1.90:10000
  start_page: lst::index.adoc
  #start_page: component-b::index.adoc
content:
  sources:
#  - url: https://gitlab.com/antora/demo/demo-component-a.git
#    branches: HEAD
#    # setting edit_url to false disables the Edit this Page link for any page that originates from this repository
#    # the same thing can be achieved by adding empty credentials (i.e., @) in front of the domain in the URL
#    edit_url: false
 # - url: https://gitlab.com/antora/demo/demo-component-b.git
#    branches: [v1.0, v2.0, main]
#    start_path: docs
  - url: https://github.com/gayanov-aa/LST.git
  - url: https://gayanov-aa:Lazuri15@github.com/TKAlpha/ProjectDocs.git
#  - url: https://gitlab.com/antora/demo/docs-site.git
    branches: HEAD
asciidoc:
  attributes:
    experimental: ''
    idprefix: ''
    idseparator: '-'
    page-pagination: ''
    plantuml-server-url: "https://plantuml.gitlab-static.net"
    plantuml-fetch-diagram: true
  extensions:
  - asciidoctor-plantuml

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable

