=== ОКРП UC1  Претензия покупателя OUT

<<home, К оглавлению>>

[cols="1,2"]
|===
|*Система*
| LST (рабочая область по работе с отклонениями)

|*Основное действующее лицо*
|Клиент, менеджер по работе с отклонениями

|*Цель*
a|Создать унифицированное окно обработки претензий OUT с возможностью ручного или автоматизированного занесения информации.

|*Триггер*
a|Клиент создал претензию в канале продаж (ЛИ - УПП ЛИ, выгрузка из УПП ЛИ - целевое автоматическая выгрузка из УПП ЛИ;
DL/РЕНО - присылают на почту руками - целевой через WEB интерфейс доступный клиенту создавать претензию; 
OZON - передаётся через обмен с порталом.;
 )

|*Предварительные условия*
a|. Заполнение обязательных полей в претензии (№ реализации, № ТМ, тип отклонения, количество,), 
. Проверка на сроки выставления претензий
. Наличие претензионных материалов

|*Результат*
| Выдача решения по каждой позиции рассматриваемой претензии

|*Постусловия*
|Разрешение на проведение корректировок, оформление возврата.

|*Отклонения*
a| . Неправильно оформленная претензия, передача клиенту мотивированного отказа

|*Допущения*
|


|*Бизнес-правила*
a|  *БПР1:* Заполненны все обязательные поля и реквизиты

*БПР2:* Претензия актуальна в пределах сроков выставления претензий согласно договора

|*Не решённые вопросы*
a| 

|===


.Основной поток событий.

[cols=".<1,.^2,>.4", greed=rows, options=header]
|===
|№ Шага
|Действующее лицо
|Описание шага

|UC1.1
|Клиент
a| *оформление претензии OUT через обмены (ABOM/OZON/УПП ЛИ)*

. В собственном приложении оформляет претензию OUT
. Передает претензию OUT через обмены

|UC1.2
|Клиент
a|*Оформление претензии OUT через WEB-интерфейс*

. оформляет претензию OUT


|UC2
|Система
a|*Проведение проверки на правильность заполнения претензии OUT*

. Проверка заполнения обязательных полей
.. Проверка корректности номера тарного места
.. Проверка корректности номера реализации
. Проверка на корретность сроков выставления претензий OUT (сравниваем текущую дату, с датой реализации)
. Отправка сообщения пользователю о успешно/не успешно оформленной претензии OUT
. Проведение пртензии OUT

|UC3
|Менеджер по работе с отклонениями
a|*Проведение расследования (смена статуса "вина склада" по строчно!!!) претензии OUT*

. Открыть претензию OUT, рассмотреть претензионные документы
.. Отказ (информирование пользователя с причинами)
.. Вины склада нет (претензионная работа с поставщиком/перевозчиком) документ претензии должен наследовать номера корректирующих документов поступления/реализации + создание *претензии IN (см.UC оформление претензии IN)* на основании претензии OUT
.. Вина склада есть (расследование претензий OUT внутри склада, проведение корретировок в УПП) документ претензии OUT должен наследовать номера корректирующих документов + при необходимости указать ссылку на Акт об расхождении (либо создать на основании).
. Возможная смена статуса
. Информирование клиента о изменении состояния претензии OUT

|UC4
|Менеджер по работе с отклонениями
a|*Удовлетворение претензии*

. Проведение возврата (см. UC5 Проведение возврата)
. Изменение статуса претензии OUT на основании обменов по результату приёмки
.. Принято без отклонений
.. Принято с отклонениями
.. Не принято
. Проведение корретировок в УПП, информаци о корректировках наследуется в претензию OUT
. Информирование клиента о проведении корректировки (статусе претензии OUT)
. Изменение статуса претензии OUT на "Закрыта"

|===


=== ОКРП UC2  Претензия поставщику IN

<<home, К оглавлению>>

[cols="1,2"]
|===
|*Система*
| LST (рабочая область по работе с отклонениями)

|*Основное действующее лицо*
|Поставщик, менеджер по работе с отклонениями, *поклажедатель*

|*Цель*
a|Создать унифицированное окно обработки претензий IN с возможностью ручного или автоматизированного занесения информации.

|*Триггер*
a| . Смена статуса строк в претензии OUT на "Вины склада нет"
. Закрытие приемки с расхождениями получаемыми через обмены
. Ручное создание претензии IN

|*Предварительные условия*
a| . Наличие проведенного документа поступления УПП

|*Результат*
| Получение решение по каждой позиции рассматриваемой претензии IN

|*Постусловия*
|Разрешение на проведение корректировок, оформление возврата поставщику.

|*Отклонения*
a|

|*Допущения*
| Все поставщики работают через WEB-обмен или формализованные шаблоны сообщений через электронную почту


|*Бизнес-правила*
a|  *БПР1:* 

|*Не решённые вопросы*
a| . Как взаимодействовать с поставщиками через какие каналы связи? вопрос к ПИЮ

|===


.Основной поток событий.

[cols=".<1,.^2,>.4", greed=rows, options=header]
|===
|№ Шага
|Действующее лицо
|Описание шага

|UC1
|Система, менеджер по работе с отклонениями
a| *оформление претензии IN по шаблону*

Шаблон претензии IN - настраиваемый по определенным критериям алгоритм, заполняющий реквизиты претензии IN и выполняющий набор действий по созданию претензионных материалов (настроенные печатные формы пример: ТОРГ2/М7/ТТН/Акт приёма-передачи)


. Создается претензия IN
. На основании определенных критериев применяется шаблон оформления претензии IN(автоматически заполняются обязательные поля + применяются печатные формы для возможности вывода на печать)
.. Поставщик
.. Владелец товара
.. и т.д.
. Применить статус претензии IN `"Новая"`

|UC2
|менеджер по работе с отклонениями
a| *акцептование/закрытие претензии IN*

. Проверить правильность заполнения полей и при необходимости скорректировать 
. Прикрепить к претенизии IN фотоматериалы
. Генерация подписанных печатных форм с подписью и печатью в формате `.pdf/xlsx` и прикрепление к претензии IN
. оформить решение
. ручная смена статуса претензии IN
.. `"акцептовано"`
.. `"закрыто"`
. Если "акцептовано", отправляем автоматически письмо поклажедателю, поставщику с вложениями претензионных материалов и претензией IN
. поставить признак в претензии IN "Письмо отправлено!"

|UC3
|менеджер по работе с отклонениями
a| *смена статусов по претензии IN*

. Получить решение от поставщика/поклажедателя
. Проставить в претензии IN по каждой строке статус решения
.. Отказано
.. Возврат излишков
.. Возврат дефектной детали
.. Возврат излишков дефектной детали
.. Утилизация
.. Оформление корректировочной С/Ф
. Возврат поставщику *(см. UC5)*
. ручная смена статуса претензии IN
.. отозвана
.. отказано
.. частично удовлетворено
.. ожидаем корректировки
. По факту проведения корректировок создается ссылка на корректировки в УПП (ERP)

|===


=== ОКРП UC3  Приоритезация рассмотрения претензий IN/OUT

<<home, К оглавлению>>

[cols="1,2"]
|===
|*Система*
| LST (рабочая область по работе с отклонениями)

|*Основное действующее лицо*
| Система, администратор рабочей области по работе с отклонениями отдела ОКРП

|*Цель*
a| . Приоритезировать претензии на основании настраиваемых критериев
. Возможность гибкой настройки справочника контрагентов для автоматизированного присвоения приоритетов претензий и назначение `кодов приёмки`
. Распределение претензий на исполнителей (администрирование)

|*Триггер*
a| . создание претензии
. ручное изменение приоритета

|*Предварительные условия*
a| . Заполненные условия в НСИ справочник контрагентов
.. сроки выставления претензий IN
.. сроки рассмотрения претензий OUT
. претензия IN не в статусе "Новая"

|*Результат*
a|. Автоматическая сортировка претензий по приоритету и сроку выставления  или рассмотрения.
. Назначение претензии на исполнителя

|*Постусловия*
|

|*Отклонения*
a| . Незаполнено НСИ справочник контрагента - выставляется приоритет по умолчанию (настраиваемый) (срок 20 дней  - может быть настраиваемый)
. Если условия приоритета и сроков совпадают, то дополнительные критерии по количеству строк в претенизии или стоимости отклонений в руб.


|*Допущения*
|

|*Бизнес-правила*
a|  *БПР1:* 

|*Не решённые вопросы*
a| 

|===


.Основной поток событий.

[cols=".<1,.^2,>.4", greed=rows, options=header]
|===
|№ Шага
|Действующее лицо
|Описание шага

|UC1.1
|Система
a| *Сортировка претензий, согласно приоритета и срока выставления претензии IN*

. При создании претензии проводится проверка на заполненные условия НСИ в справочнике контрагентов и сверяются даты срока выставления претензий и текущей даты
.. просрочено < 0
.. критическая сегодня
.. срочная -  < 2 дней
.. обычная < 5 дней но >2 дней
.. не срочная > 5 дней

Сроки претензии рассчитываются гибко исходя из предварительно настраиваемой матрицы приоритетов:

. Тип претензии (влияет на выбор матрицы)
. Сложность (Указывается специалистом по работе с отклонениями в момент обработки претензии)
. Срочность (настраивается в матрице)

Приоритезированные строки расскашиваются в цвета

|UC1.2
|Система
a| *Сортировка претензий, согласно приоритета и срока выставления претензии OUT*

. При создании претензии проводится проверка на заполненные условия НСИ в справочнике контрагентов и сверяются даты срока рассмотрения претензий и текущей даты
.. просрочено < 0
.. критическая < 3 дней
.. срочная -  < 7 дней
.. обычная < 5 дней но >2 дней
.. не срочная > 5 дней

Сроки претензии рассчитываются гибко исходя из предварительно настраиваемой матрицы приоритетов:

. Тип претензии (влияет на выбор матрицы)
. Сложность (Указывается специалистом по работе с отклонениями в момент обработки претензии)
. Срочность (настраивается в матрице)

Приоритезированные строки расскашиваются в цвета

|UC2
|администратор рабочей области по работе с отклонениями отдела ОКРП
a| *Распределение претензий на исполнителей*

. Появилась новая претензия
. Ожидание распределения на исполнителя (по истечению регламентного времени, если претензия не распределена, происходит эскалация на отв. руководителя  -  email)
. Претензия распределена (Необходима возможность повторного перераспределения претензий на исполнятеля + групповое распределение нескольких претензий)

|UC3
|администратор рабочей области по работе с отклонениями отдела ОКРП
a| *График доступности специалистов*
. В календарном графике вносить не доступных специалистов
. В диалоге передачи заявок недоступного специалиста система предлагает перераспределить на специалилста с наименьшим числом заявок

|===

=== ОКРП UC4 Оформление выявленного отклонения

<<home, К оглавлению>>

[cols="1,2"]
|===

|*Система*
| LST (рабочая область по работе с отклонениями)

|*Основное действующее лицо*
| Система, администратор рабочей области по работе с отклонениями отдела ОКРП

|*Цель*
a| . Упорядочить учет отклонений, совершенных сладом
. Иметь возможность использовать статистику для выявления проблем
. Увеличить производительность за счет автоматизации создания Актов

|*Триггер*
a| . После выявления инцидента

|*Предварительные условия*
a| . Информация об отклонении

|*Результат*
a| . Запись в реестре Актов отклонений 
. Заполненная печатная форма

|*Постусловия*
|

|*Отклонения*
a| 


|*Допущения*
|

|*Бизнес-правила*
a|  *БПР1:* 

|*Не решённые вопросы*
a| 

|===


.Основной поток событий.

[cols=".<1,.^2,>.4", greed=rows, options=header]
|===
|№ Шага
|Действующее лицо
|Описание шага

|UC1. Оформление выявленного отклонения
|администратор рабочей области по работе с отклонениями отдела ОКРП
a| *Оформленный Акт об отклонениях*

. Создание нового документа - заполнение обязательных полей
. Установка статуса при создании "Черновик"
. Прикрепление материалов расследования
. Связь с претензией
. Ручная смена статуса "На рассмотрении"
. Печать Акта об расхождении

|UC2. Проведение расследования и фиксация в резульататах выявленного отклонения
|администратор рабочей области по работе с отклонениями отдела ОКРП
a| *Заполнение результатов выявленного отклонения*

. Заполнение обязательных полей по результатам выявленных отклонений
. Печать протокола расследования
. Ручная смена статуса "На исполнении"/"Закрыто"

|===


=== ОКРП UC5 Учет возвратов

<<home, К оглавлению>>

[cols="1,2"]
|===

|*Система*
| LST (рабочая область по работе с отклонениями)

|*Основное действующее лицо*
| Система, специалист по работе с отклонениями отдела ОКРП

|*Цель*
a| . Упорядочить учет возвратов от контрагентов
. Иметь возможность использовать статистику для выявления проблем
. Увеличить производительность за счет автоматизации организации возвратов

|*Триггер*
a| . Информирование клиента о изменении состояния претензии OUT по каждой строке статус решения
. Проставить в претензии IN по каждой строке статус решения

|*Предварительные условия*
a| Изменение строки претензии на статус "Возврат *"

|*Результат*
a| . Выдача задания на склад
. Смена статуса по строке записи реестра возвратов

|*Постусловия*
|

|*Отклонения*
a| . Смена решения по возврату - иметь возможность убрать запись из реестра возвратов


|*Допущения*
|

|*Бизнес-правила*
a|  *БПР1:* 

|*Не решённые вопросы*

a| . Как будут формироваться запросы в TMS на вывоз товара от клиента? Как будет проходить аналогичная процедура по вывозу претензионного товара с наших складов? *_уточнить у КЕА и ТКА_*
. Продумать какой процесс автоматизированного формирования доверенностей из рабочей области оператора будет в LST *_уточнить AAA_*
. Как оператор склада будет прикреплять сканы возвратных ТСД к ЗнО/ЗнП *_уточнить AAA_*
. Какими документами подтверждается ЗнО и ЗнП по претензиям, какие документы создают бухгалтера на основе учета возвратов ? *МС*
|===


.Основной поток событий.

[cols=".<1,.^2,>.4", greed=rows, options=header]
|===
|№ Шага
|Действующее лицо
|Описание шага

|UC1.
|специалист по работе с отклонениями отдела ОКРП
a| *Поместить выбранные строки из претензии в реестр*

. после смены статуса решения по конкретной строке, выбирает строки и указывает количество, владельца товара
. строки добавляются в реестр
. строке реестра возвратов присваивается статус "новый" (строка доступна для добавления в ЗнО/ЗнП)

|UC2 
|специалист по работе с отклонениями отдела ОКРП
a| *Выдача ЗнО/ЗнП на возврат*

. В регламентное время вручную формируем по строкам из реестра и контрагентам документы ЗнО/ЗнП (должна быть возможность гибко выгружать по конкретному контрагенту и строкам, периоду)
. Система помещает строки в пустой рейс
. В регламентное время, полезный объём ЗнО/ЗнП выгружается в TMS (*_согласовать порядок выгрузки претензионных ЗнО/ЗнП в TMS с УСЛ_*)
. Назначен рейс обменами из TMS
. Выдача ЗнО/ЗнП на склад + формирование доверенности на получение груза (*_надо будет продумать процесс формирования доверенности оператором склада из рабочей области_*)
. Смена статуса строки из реестра "На исполнении" по факту выдачи ЗнО/ЗнП
. В записи реестра добавляется ссылка на ЗнО или ЗнП

|UC3 
|специалист по работе с отклонениями отдела ОКРП
a| *Контроль отгрузки/получения товара*

. После подтверждения ЗнО/ЗнП строка реестра меняет статус отгрузки/получения (подсвечивается зеленым) 
.. Полностью отгружен/принят - зеленый
.. Частично отгружен/принят - желтый
.. Не отгружен/принят - красный
. Вручную можем поменять статус отгрузки/получения

|UC4 
|специалист по работе с отклонениями отдела ОКРП
a| *Получение ссылки на сканированные возвратные ТСД*

. По факту получения документов возвратных ТСД, оператор прикрепляет сканы к документам ЗнО/ЗнП - *_уточнить у ААА_*
. При появлении прикрепленных документов возвратных ТСД в ЗнО/ЗнП в реестре возвратов создается ссылка на сканы
. Смена статуса строки реестра возвратов на "Принят/отгружен" либо "Ошибки в ТСД"


|UC5 
|специалист по работе с отклонениями отдела ОКРП
a| *Передача данных для корректировки в бухгалтерию*

. В регламентное время формируется и отправляется реестр возвратов на корректировку в бухгалтерию (стандартная форма)
. Запись реестра возвратов меняет статус "На корректировке"

|UC6 
|специалист по работе с отклонениями отдела ОКРП
a| *Смена статуса на "Закрыто" в реестре возвратов*

. Создана корректировка в УПП (ERP)
. В претензии создается ссылка на корректировку
. В строке реестра возвратов, меняется статус "Закрыто"

|===

=== ОКРП UC6 Установка кодов приёмки

<<home, К оглавлению>>

[cols="1,2"]
|===

|*Система*
| LST (рабочая область по работе с отклонениями)

|*Основное действующее лицо*
| Система,  Администратор области по работе с отклонениями

|*Цель*
a| . Настройка матрицы кодов приёмки
. Выдача кодов приёмки в ЗнП

|*Триггер*
a| Создание документа ЗнП

|*Предварительные условия*
a| Настроенная матрица кодов приёмки

|*Результат*
a| Присвоение кода приёмки строке в ЗнП

|*Постусловия*
| 

|*Отклонения*
a| Не настроена матрица кодов приёмки  - устанавливаются значения по умолчанию.


|*Допущения*
| Данный механизм распространяется на все ЗнП, включая ЗнП на возврат

|*Бизнес-правила*
a|  *БПР1:* 

|*Не решённые вопросы*

a| 

|===


.Основной поток событий.

[cols=".<1,.^2,>.4", greed=rows, options=header]
|===
|№ Шага
|Действующее лицо
|Описание шага

|UC1.
|Администратор рабочей области по работе с отклонениями
a| *Заполненная матрица кодов приемки*

. Заполняется матрица в соответствии с условиями сочетание признаков:
.. Контрагент
.. Группа товаров (см в справочнике Номенклатура)
.. Номенклатура

|UC2.
|Администратор рабочей области по работе с отклонениями
a| *Заполнение кодов приёмки при создании ЗнП*

. При создании ЗнП, проводится сравнение условий, настроенных в матрице кодов приёмки, и присвоение строке документа кода приёмки. Если сочетание значений в матрице не найдено, то устанавливается значение по умолчанию. До выгрузки ЗнП на склад, вручную можно переопределять значение кода приёмки по строке.

|===

=== ОКРП UC7 Управление отклонениями в хранении

<<home, К оглавлению>>

[cols="1,2"]
|===

|*Система*
| LST (рабочая область по работе с отклонениями)

|*Основное действующее лицо*
| Система,  Администратор области по работе с отклонениями

|*Цель*
a| . Упорядочить работу по учёту отклонений в разрезе всех складских площадок
. Увеличить производительность за счет автоматизации фиксации, разбора и устранения отклонений
. Планирование проведения инвентаризаций


|*Триггер*
a| . Проведение инвентаризации ответ при подтверждении "LOST", "БРАК"
. В процессе отбора по заданиям ЗнО/ЗнП ответ при подтверждении "LOST", "БРАК"

|*Предварительные условия*
a|

|*Результат*
a| . Проведение учёта выявленных отклонений
. Выдача документа выборочных инвентаризаций в складские системы

|*Постусловия*
| 

|*Отклонения*
a| 

|*Допущения*
| 

|*Бизнес-правила*
a|  *БПР1:* 

|*Не решённые вопросы*

a| 

|===


.Основной поток событий.

[cols=".<1,.^2,>.4", greed=rows, options=header]
|===
|№ Шага
|Действующее лицо
|Описание шага

|UC1.
|Специалист рабочей области по работе с отклонениями
a| *Создание документа выборочной инвентаризации*

. Поступило распоряжение на проведение инвентаризации либо проведение расследования, ввод документа на основании претензии. Создаем документ выборочной инвентаризации.
. Наполняем документ строками. Проводится проверка наличия товара в остатках учетной системы (остатки в УПП), если нет, строка не добавляется.
. Указываем тип инвентаризации:
.. без резервирования остатков (без блокирования остатков к отгрузке)
.. резервирование остатков (блокировка остатков к отгрузке)
. Указываем владельца товара:
.. Одного владельца
.. Список владельцев
.. Не указанно, тогда по всем владельцам
. Склады инвентаризации
.. Один склад
.. Список складов по площадке
.. Если не указанно, то все склады по площадке
. Складская площадка (РС)
. Тип инвентаризации (устанавливается опционально)
.. По претензии
.. Выборочная инвентаризация
.. Годовая инвентаризация - полная
.. Годовая инвентаризация - выборочная
. Устанавливаем статус "Новый"

|UC2.
|Специалист рабочей области по работе с отклонениями
a| *Выдача выборочной инвентаризации в работу и подтверждение выполнения*

. Устанавливаем статус "Обрабатывается"
. Документ обменами выгружается в WMS
. Если выгрузка успешная, меняется статус "В работе", иначе "Не выгружено"
. После выполнения задания, WMS обменами передает результаты выполнения. (количество по строке + отклонения), в документе выборочной инвентаризации фиксируются результаты.
. Меняется статус на "Завершено"

|UC3.
|Специалист рабочей области по работе с отклонениями
a| *Создание записи в реестре отклонений*

. Получен ответ по документам ЗнО/ЗнП/Производственное задание(Выборочная инвентаризация), при подтверждении  "LOST", "БРАК", излишек
. По каждой строке создается запись в реестре отклонений, указывается ссылка на документ претензии
. Устанавливается статус "Новый"
. Указать тип отклонения (наследуется из задания ЗнО/ЗнП/ПрЗ)
.. По претензии
.. Выборочная инвентаризация
.. Годовая инвентаризация - полная
.. Годовая инвентаризация - выборочная
. Устанавливается количество расхождений по SKU между WMS и ERP на момент записи в реестре отклонений
. Указать склад
. Возможность корректировать запись вручную

|UC4.
|Специалист рабочей области по работе с отклонениями
a| *Занесение результатов расследования в реестр отклонений*

. Указать решение
. Указать виновника
. Указать комментарий
. Сменить статус (вручную) "Рассмотрено"

|UC5.
|Специалист рабочей области по работе с отклонениями
a| *Устранение отклонения*

. При необходимости создать на основании претензию IN (см UC2 Претензия поставщику IN)
. Создать и распечатать акт об отклонении на виновника (см UC4 Оформление выявленного отклонения)
. Сменить статус на "На устранении"
. После устранения отклонения вручную сменить статус на "Закрыт"

|UC6.
|Специалист рабочей области по работе с отклонениями
a| *Передача фактического результата пересчета*

. При необходимости результаты производственного задания, с типом выборочная инвентаризация, можно выгрузить (вручную) в документ инвентаризации ERP

|===

=== ОКРП UC8 Устранение отклонений (выдача производственных заданий)

<<home, К оглавлению>>

[cols="1,2"]
|===

|*Система*
| LST (рабочая область по работе с отклонениями)

|*Основное действующее лицо*
| Система,  Администратор области по работе с отклонениями

|*Цель*
a| . Выдача производственных заданий


|*Триггер*
a| . На основании документа отклонения (в т.ч. претензий)
. потребности в производственных задачах цеху

|*Предварительные условия*
a| . наличие зафиксированных отклонений

|*Результат*
a| . отработанное производственное задание

|*Постусловия*
| обязательная установка статуса по каждой строке из задания

|*Отклонения*
a| 

|*Допущения*
| 

|*Бизнес-правила*
a|  *БПР1:* 

|*Не решённые вопросы*

a| . Справочник работ производственных заданий Смирнов
. Сверить частный случай выдачи производственного задания - частичная инвентаризация UC7 на логические ошибки
|===


.Основной поток событий.

[cols=".<1,.^2,>.4", greed=rows, options=header]
|===
|№ Шага
|Действующее лицо
|Описание шага

|UC1.
|Специалист рабочей области по работе с отклонениями, поклажедатель, 
a| *Создание и выдача документа производственное задание*

. На основании документа претензии, ручной ввод создается документ "Производственное задание" (Создание нового Производственного задания на основании закрытого старого)
. Устанавливается статус документу "Новый"
. Наполнение документа строками SKU
.. строки на основании документа претензии
.. выбор строк с фильтром по отклонениям
.. выбор неисполненных строк - если делаем на основании закрытого производственного задания
.. произвольный выбор
. Заполняем шапку документа
.. тип задания (код характеризующий вид работ)
.. площадка/склад
.. владелец товара
.. плановая дата/время начала работ (по умолчанию текущее) может устанавливаться в ручную
.. плановая дата/время окончания работ (по умолчанию пустое)
. Проверка табличной части в зависимости от выполняемых работ и информирование о прохождении проверки (визуально подсвечивать отклонения)
.. Переупаковка  - рассчитываем количество исходя из нормы и проверяем остатки тары
.. Частичная инвентаризация  - наличие остатков в учете
.. и т.д.
. Записываем документ
. Выдаём документ в работу
. Обменами документ выгружается в LM
. LM назначает плановую дату выполнения задания и выгружает задание в WMS
. Устанавливается статус "Выгружен" и записывается плановая дата выполнения из LM


|UC2.
|Специалист рабочей области по работе с отклонениями
a| *Подтверждение документа производственное задание*

. WMS передает подтверждение в LM
. Обменами из LM передается подтверждение о выполнении производственного задания 
.. (ответ по каждой строке) Задание может выполняться частично. 
.. Передается обработанное количество или признак (количество) частичной не отработки
.. количество и код отклонения по строке
. Меняем статус на "исполнен"

|UC3.
|Специалист рабочей области по работе с отклонениями
a| *Настройка справочника кодов работ для документа производственное задание*

. выгружается (синхронизируется) список работ через обмены с ERP(УПП)
. пока не знаем, но могут быть дополнительные атрибуты для обогащения в LST. 
|===

=== ОКРП UC9 Фиксация отклонений на основании сверки баз

<<home, К оглавлению>>

[cols="1,2"]
|===

|*Система*
| LST (рабочая область по работе с отклонениями)

|*Основное действующее лицо*
| Система,  Специалист по работе с отклонениями

|*Цель*
a| . Зафиксировать отклонение на основании расхождения остатков ИС 1С и WMS

|*Триггер*
a| . Выявление расхождения остатков при сверке баз

|*Предварительные условия*
a| . доступность информации о остатках товаров получаемых через обмены на один и тот же момент времени

|*Результат*
a| . Сформированный  отчет о расхождении остатков ИС 1С и WMS
. Запись в реестре отклонений на основании отчета о расхождениях остатков

|*Постусловия*
| 

|*Отклонения*
a| Недоступность сервисов 1C и WMS  - предупреждение пользователя

|*Допущения*
| 

|*Бизнес-правила*
a|  *БПР1:* 

|*Не решённые вопросы*

a|
|===


.Основной поток событий.

[cols=".<1,.^2,>.4", greed=rows, options=header]
|===
|№ Шага
|Действующее лицо
|Описание шага

|UC1.
|Специалист рабочей области по работе с отклонениями
a| *Формирование отчета о расхождении остаков между базами*

. Получаем данные по остаткам из складских систем 
.. WMS под нашим управлением - через обмены
.. Складские операторы  - через файловую выгрузку, обмены
. Запрашиваем и получаем остатки в учетной системе (ERP) на момент формирования отчетности по полученным данным из складской системы
. Формируем отчет с выявленными расхождениями остатков между ИС WMS и ERP
. Выбираем выявленные расхождения, и создаем на основании записи в реестре отклонений

|===

=== ОКРП UC10 Автоматизация корректировки учета

<<home, К оглавлению>>

[cols="1,2"]
|===

|*Система*
| ERP, OMS, LST (рабочая область по работе с отклонениями)

|*Основное действующее лицо*
| Система,  Специалист по работе с отклонениями

|*Цель*
a| . Уменьшить трудоемкость связанную с необходимость корректировать учет в ERP
(На основании потери или брака создавать перемещения на соответствующие склады учета)

|*Триггер*
a| . Команда на перемещение со склада Брака или Потерь переданное обменами от WMS (см обмен MOVE Загружено по данным склада из файла XML E:\MNT&Obmen\mnt\alfa1\hist\in\2022_7\20220713142835_00012502_move.xml)

|*Предварительные условия*
a| . Наличие товара в учетной системе (на складе с которого перемещаем)
. _Товар должен находиться в свободном остатке - надо проверить!_

|*Результат*
a| . Сформированное перемещение в учетной системе ERP

|*Постусловия*
| Запись результатов попытки перемещения товаров (в ERP), в реестре отлонений

|*Отклонения*
a| Остуствие остатка в учетной системе

|*Допущения*
| Наличие соответствующего функционала автоматизированного перемещения на склад Брака или потерь в ERP

|*Бизнес-правила*
a|  *БПР1:* Перемещение должно выоляться при любом выявленном отклоении Брак или LOST

|*Не решённые вопросы*

a|
|===


.Основной поток событий.

[cols=".<1,.^2,>.4", greed=rows, options=header]
|===
|№ Шага
|Действующее лицо
|Описание шага

|UC1.1
|Специалист рабочей области по работе с отклонениями
a| *Перемещение товара на склад*

. Получаем команду от ИС WMS через обмен MOVE (переместить со склада на склад)
. По результатам перемещения от ERP получаем ответ
. Записываем результат в реестр отклоений
.. Товар перемещен на склад *
.. Товар не перемещен на склад + причина

|===
