:toc: top

=== TMS UC1 Планирование рейса

<<home, К оглавлению>>

[cols="1,2"]
|===
|*Система*
| TMS Magenta

|*Основное действующее лицо*
| Специалист по логистике

|*Цель*
a| Заказ оптимального количества транспорта под имеющийся или плановый объём и назначение его на рейс

|*Триггер*
a| При наступлении контрольного времени заказа ТС, согласно логистического стандарта

|*Предварительные условия*
| Выгруженые объёмы по фактическим ЗнО через обмены, наличие прогнозных объёмов из TMS

|*Результат*
|Создание заказа с оптимальным кол-вом ТС под планируемые объёмы и создание рейса с присвоением ТС

|*Постусловия*
| Передача заказа на ТС в портал перевозчика

|*Отклонения*
a| . Отсуствие объёмов для заказа ТС - принимаем решение не делать заказ 
. Заказов недостаточно для заказа ТС - решение принятое специалистом по логистике не делать заказ (автоматизации нет)
. *Отказ от подтвержденного ТС*

|*Допущения*
|


|*Бизнес-правила*
a|  *БПР1:* руководствуемся SLA, касаемо отмены ТС

*БПР2:* учитывать какие ТС может принимать грузополучатель (объём, характеристики ТС)

|*Не решённые вопросы*
a|. Как происходит оповещение и отказ от рейса в случае форсмажоров (поломка ТС) отмена подтвержденного ТС в TMS?  - вопрос Черкасову
. Как будут согласовываться дополнительные объёмы с УСЛ сверх согласованного плана? - вопрос к РВГ

|===


.Основной поток событий.

[cols=".<1,.^2,>.4", greed=rows, options=header]
|===
|№ Шага
|Действующее лицо
|Описание шага

|UC1
|Специалист по логистике
a| *Выгрузка через обмен созданного рейса*

. Планирование рейса
. Заказ а/м
. Присвоение рейсу заказанного а/м
. Выгрузка информации по рейсу через обмены


|===


=== TMS UC2 Формирование протокола согласования цен

<<home, К оглавлению>>

[cols="1,2"]
|===
|*Система*
| УПП / целевая  область транспортной логистики

|*Основное действующее лицо*
| Старший специалист по логистике

|*Цель*
a| Фиксация и согласование тарифов для перевыставления на заказчиков транспортных услуг

|*Триггер*
a| Проведение тендера на выбор поставщика транспортных услуг, выставление поставщиком КП, формирование на основании КП собственного предложения (цены)

|*Предварительные условия*
|

|*Результат*
a| Создание записи в регистре протокол согласования цен, для последующего формирования транспортного отчета и актов для перевыставления

|*Постусловия*
| Подписание документа по согласованию протокола цен у заказчика транспортных услуг.

|*Отклонения*
a| 

|*Допущения*
|


|*Бизнес-правила*
a|  *БПР1:*  Фактический тариф не должен превышать цен из протокола, если цена не соответствует, необходимо заново пересогласовывать. Новые направления, рассчитываются на основании КП от перевозчика.

*БПР2:* 

|*Не решённые вопросы*
a|. В чем измеряется реестр цен? *ЕКЦ*

|===


.Основной поток событий.

[cols=".<1,.^2,>.4", greed=rows, options=header]
|===
|№ Шага
|Действующее лицо
|Описание шага

|UC1
|Специалист по логистике
a| *Проведение тендера, получение цен КП*

. Получить из логистического стандарта направления (через выгрузку из TMS) (функционала нет, подумать как реализовать в области транспортной логистики или в TMS)
. Сформировать ТЗ для тендера - печатная форма с направлениями лог. стандарта (функционала нет, подумать как реализовать в области транспортной логистики или в TMS)
. Разослать ТЗ для тендера по перевозчикам (функционала нет, подумать как реализовать в области транспортной логистики или в TMS)
. Получение КП от перевозчика - через email
. Проведение тендера, определение победителей, распределение - ручные действия.
. Оформление доп. соглашений с перевозчиком
. Запись плановых цен перевозчика в  области транспортной логистики
. Расчет и запись цен тарифов для перевыставления заказчикам транспортных услуг

|===

=== TMS UC3 Формирование заявок на оплату

<<home, К оглавлению>>

[cols="1,2"]
|===
|*Система*
| УПП / целевая  область транспортной логистики

|*Основное действующее лицо*
| Специалист по логистике

|*Цель*
a| . Сформировать заявку на оплату
. Повысить производительность за счет автоматизации формирования заявок на оплату

|*Триггер*
a| . Получение от перевозчика правильно оформленного комплекта товаро-сопроводительных документов (ТСД)

|*Предварительные условия*
a| . Документы ТСД правильно оформлены и в полном комплекте
. В реестре рейсов подлежащих оплате автоматически создана запись с данными по рейсу

|*Результат*
a| Согласованная заявка на оплату

|*Постусловия*
| 

|*Отклонения*
a| . Неправильно оформленные документы
. Отклоненная заявка на расход ДС
. Просрочена оплата по заявке на расход ДС

|*Допущения*
|


|*Бизнес-правила*
a|  *БПР1:*  Оплата перевозчику производится после получения полного комплекта ТСД с учетом отсрочки из договора

*БПР2:* Срок возврата документов, должен соответствовать срокам прописанным в договоре

|*Не решённые вопросы*
a|

|===


.Основной поток событий.

[cols=".<1,.^2,>.4", greed=rows, options=header]
|===
|№ Шага
|Действующее лицо
|Описание шага

|UC1
|Специалист по логистике
a| *Контроль Реестра рейсов подлежащих оплате*

. В реестре рейсов подлежащих оплате автоматически создана запись с данными по рейсу
. В рейсе проставляется *плановый срок* предоставления документов - плановый срок рассчитывается из договора отсрочка предоставления документов + даты выгрузки последнего контрагента по маршруту
. Производится проверка дат предоставления ТСД. Если Текущая дата больше плановой даты планового срока предоставления документов, и информация о платежных документах не заполнена, то присваивается статус "Просрочены ТСД" и запись визуально выделяется.


|UC2
|Специалист по логистике
a| *Создание записи в Реестре рейсов подлежащих оплате*

. Получаем оригиналы ТСД или электронные через ЭДО
. Проверяем комплектность, корректность документов
. Реестр рейсов подлежащих оплате добавляются данные в запись реестра:
.. информацию о платёжных документах (сумма, номер, дата, статья ДДС, договор)
. Записи присваивается статус "новая"
. В ЭДО подписываются акты на основании рейса подлежащих оплате, в записи указывается признак "акты подписаны".  Если от даты создания записи реестра рейсов подлежащих оплате больше 3-х дней и не установлен признак "акты подписаны", производится информирование пользователя
. желаемая дата оплаты - нужна для компоновки нескольких рейсов в одну заявку на расход ДС


|UC3
|Специалист по логистике
a| *Создание заявки на оплату*

. Выбираем желаемую дату оплаты
. Формируем заявки (автоматизированно заполняются реквизиты + обоснование платежа)
. Заявки на расход ДС создаются в УПП (ERP)
. Прикрепляется ссылка в записи реестра рейсов подлежащих оплате на соответствующую заявку расхода ДС
. В записи меняется статус на "Заявка подана"
. Если заявка на расходование ДС отклонена, то меняется статус записи "заявка на оплату ДС отклонена", пользователь должен иметь возможность повторно сгенерировать новую заявку на оплату, тогда статус опять должен поменяться на "Заявка подана"

|UC4
|Специалист по логистике
a| *Оплата по заявке*

. Производится оплата по заявке на расход ДС (создается платежное поручение)
. в записи реестра рейсов подлежащих оплате, создается запись даты оплаты
. Если заполнена дата оплаты запись меняет статус на закрыта (убрана из активного списка, серая, итд)
. Если дата оплаты не заполнена, и текущая дата больше желаемой даты оплаты, запись визуально выделяется и меняется статус на "оплата по заявке просрочена" 
. Если количество дней отсрочки платежа по перевозчику от даты предоставления ТСД меньше чем текущая дата, то запись меняет статус "оплата перевозчику просрочена"


|===


=== UC4 Претензионная работа

<<home, К оглавлению>>

[cols="1,2"]
|===
|*Система*
| УПП / целевая  область транспортной логистики

|*Основное действующее лицо*
| Специалист по логистике

|*Цель*
a| Оплата претензии (нам или мы оплачиваем)

|*Триггер*
a| . Получен оригинал претензии от перевозчика (для входящей претензии)
. На основании отклонения факта прибытия и планового времени прибытия

|*Предварительные условия*
a| 

|*Результат*
a| . Выставление претензий
. Контроль документооборота и оплат

|*Постусловия*
| 

|*Отклонения*
a| 

|*Допущения*
|


|*Бизнес-правила*
a|  *БПР1:*  
*БПР2:* 

|*Не решённые вопросы*
a| . Как связаны претензии УТЛ с оформляемыми Актами выявленных расхождений операторами?
. Почему по претензиям связанными с ТМЦ, в вопросах взаимодействия с ТК занимается УТЛ - это не лишнее звено ? и усложнение процесса ? 

|===


.Основной поток событий.

[cols=".<1,.^2,>.4", greed=rows, options=header]
|===
|№ Шага
|Действующее лицо
|Описание шага

|UC1.1
|Специалист по логистике
a| *Фиксация инцидентов и поступивших обращений IN*

. Выявление фактов отклонения (На основании поступивших обращений от перевозчиков) - получаем письменные обращения
. Создаем претензию IN
. Устанавливаем статус "Получено"
. Сканируем полученные документы и прикрепляем к входящей претензии
. Проводим проверку полученных данных, для этого из системы должно подтягиваться фактическое время убытия транспорта со склада и плановое время убытия согласно графика из *ТТН* (см. АРМ Оператора, UC фиксация контрольных событий + планирование). Специалист сравнивает время планируемое и фактическое, данные подтягиваются автоматически при указании рейса в претензии.
. Оформляется решение по входящей претензии (шаблоны стандартных решений для быстрого заполнения)
. После оформления решения меняется статус "Подготовлен ответ" или "Отказ по претензии".
. Печатаем решение по претензии (на основании шаблона решения) или отправляем по электронной почте
. Создаем в 1С УПП заявку на оплату на основании сформированной входящей претензии
. Меняем статус "На оплате"
. Если заявка в 1С УПП согласована, статус претензии меняется на оплачен, претензия становится неактивной
. Если перевозчику был передан отказ по претензии, то ожидаем ответ, после получения ответа, меняем статус претензии на "Претензия закрыта"

|UC1.2
|Специалист по логистике
a| *Фиксация инцидентов и поступивших обращений OUT*

. Выявление фактов отклонения (*автоматизированно* на основании выявленных отклонений в рабочей области оператора)
. Создание нового документа по выявленному исходящему отклонению 
.. Сумма претензии
.. Сумма рейса
.. Ссылка на договор
.. Номер рейса
.. Перевозчик
.. Маршрут
. Установка статуса "Новый"
. Оповещение специалиста по логистике о новых претензиях (через рассылку или дашборд)
. Проверить факты отклонения по новым претензиям
.. Заполнить результат проведенной проверки
.. Основание претензии
. Установка статуса "Подготовлено"
. Печать претензии (печатаем из документа исходящей претензии) (для подписания у Начальника УТЛ), (либо отправляем на согласование через документооборот - продумать возможность создания документа на согласование в ДО и получения результатов согласования) 
. Установка статуса "Подписан" после подписания у Начальника УТЛ (согласующего претензии)
. Сохранение скана подписанного документа в претензии, для отправки по почте (если перевозчик работает не через ЭДО), или через ЭДО (продумать возможность отправки документа через ЭДО)
. Установка статуса "Ожидание оплаты"
. Производится проверка оплат. Если в течении настраиваемого времени, не произведена оплата перевозчиком (проверка оплат из УПП - связь документа претензии и реестра выписок), то происходит информирование специалиста по логистике (выкрасить строку в списке претензий)
Производится контроль сумм претензии и выписки оплат, если расхождений нет, то претензии присваивается статус "Оплачено", если суммы расходятся в большую или меньшую сторону, то происходит информирование специалиста по логистике присваивается статус "Некорректная оплата"
. На любом этапе претензия может менять статус на "Отклонена", выставляется вручную.

|===

=== UC5 ВЭД

<<home, К оглавлению>>

[cols="1,2"]
|===
|*Система*
| УПП / целевая  область транспортной логистики

|*Основное действующее лицо*
| Специалист по логистике

|*Цель*
a| Подготовка ТСД (CMR, invoice, отгрузочная спецификация, спецификация к счету, упаковочные листы) по ВЭД отгрузкам

|*Триггер*
a| . Создана реализация на контрагента
. Получена информация от склада по количеству тарных мест и номеру пломбы

|*Предварительные условия*
a| . Наличие лимитов по контрагенту
. Наличие объёмов по транзитной норме (наличие спланированного рейса)

|*Результат*
a|Оформленные товаро-сопроводительные документы

|*Постусловия*
| 

|*Отклонения*
a| . Превышение лимита - выгрузка товара превышающего лимиты
. Не выпуск декларации - ручное принятие решения по рейсу
. Когда выгружается транзитный заказ без заезда на склад, на данный момент он не попадает в рейс (попадает в рейс только заказы собираемые в Твери) - надо подумать как такие заказы обернуть в виртуальный рейс!!!!!! КЕА

|*Допущения*
|


|*Бизнес-правила*
a|  *БПР1:*  
*БПР2:* 

|*Не решённые вопросы*
a|. Когда выгружается транзитный заказ без заезда на склад, на данный момент он не попадает в рейс (попадает в рейс только заказы собираемые в Твери) - надо подумать как такие заказы обернуть в виртуальный рейс!!!!!! КЕА
. Кроме улучшений, перенести функционал из логистики в LST ? *ЕКЦ*

|===


.Основной поток событий.

[cols=".<1,.^2,>.4", greed=rows, options=header]
|===
|№ Шага
|Действующее лицо
|Описание шага

|UC1
|Специалист по логистике
a| *Проверка лимитов*

. Контрагент оплачивает товар, ФД проставляет лимиты _(уточнить название документа или регистра у ФД)_
. В логистике при печати документов производится проверка на соответствие лимитов (сумма реализации не должна превышать лимитов)

|UC2
|Специалист по логистике
a| *Формирование печатных документов*

. Заполняем условия поставки при создании нового контрагента  - настройка НСИ (должен настраиваться в справочнике контрагентов как отдельный атрибут и вставляться в печатные формы документов)
. № грузовой таможенной декларации (дополнительный атрибут устанавливается в рейсе)
. прикрепляем сканы распечатанных документов ТСД и ГТД к рейсу
. указываем в отдельном атрибуте в рейсе конечного перевозчика (текстовое поле)
. Из рейса оформляем документы по всем реализациям (распечатываем или сохраняем печатную форму)


|===


=== UC6 Разнесение счетов и актов

<<home, К оглавлению>>

[cols="1,2"]
|===
|*Система*
| УПП / целевая  область транспортной логистики

|*Основное действующее лицо*
| Специалист по логистике

|*Цель*
a| . контроль поступления ТСД
. уменьшить трудоёмкость
. проверка корректности поступаемых ТСД
. контроль передачи ТСД в бухгалтерию
. контроль поступления ТСД в срок (см UC заявки на оплату)

|*Триггер*
a| поступление документов в печатном виде или через ЭДО

|*Предварительные условия*
a| 

|*Результат*
a| . Установка статусов движения ТСД в реестре рейсов
. проведенная проверка ТСД

|*Постусловия*
| Документы переданы в бухгалтерию + реестр документов и полученный реестр обратно

|*Отклонения*
a| 

|*Допущения*
|


|*Бизнес-правила*
a|  *БПР1:*  Движение документов внутри подразделений осуществляется через реестр приёмо-передачи.

*БПР2:* 

|*Не решённые вопросы*
a|


|===


.Основной поток событий.

[cols=".<1,.^2,>.4", greed=rows, options=header]
|===
|№ Шага
|Действующее лицо
|Описание шага

|UC1
|Специалист по логистике
a| *Сверка поступивших ТСД (заполнение чек-листа)*

. В карточке контрагента должны быть указаны условия работы с ТСД, на основании настроек, должны проводиться проверки условий.
. Формируем список в реестре рейсов для проверки документов (выводятся документы с любым статусом кроме "Закрыт")
. На вновь созданную запись устанавливаем статус контроля ТСД "Новый"
. Проводим проверку на комплектность и правильность оформления
.. Проверка печати и подписи в документах (в ЭДО факт подписанного документа транслируется, если печатный документ, установка признака)
.. Комплектность документов
.. Сверка сумм счета и тарифов в логистике (для документов выставляемых транспортной компанией)
. Установить статус сверки ТСД записи реестра рейсов, "Проверено"
. По ТСД не прошедшим проверку, установить статус "Восстановление", добавляем комментарий причины.

|UC2
|Специалист по логистике
a| *Подготовка реестра передачи документов в бухгалтерию*

. Формируем реестр передачи документов, автоматически формируется печатная форма реестра приёма-передачи на выделенные позиции из списка, отбор осуществляем по записям со статусом "Проверено" и опционально по контрагенту.
. На позиции попавшие в реестр приёма-передачи устанавливается статус "Передан" и указывается дата передачи.

|UC3
|Специалист по логистике
a| *Завершение процесса контроля ТСД*

. Получаем от бухгалтерии обратную связь с результатами приемки ТСД
. На согласованные документы устанавливаем статус "Закрыт"
.. Осуществляем отбор списка по дате передачи и статусу
.. галочками выбираем все или конкретные позиции
.. применяем статус
. На не согласованные документы устанавливаем статус "Не принят!", добавляем комментарий причины.

|===

=== UC7 Выгрузка и оформление экспресс-отправлений
<<home, К оглавлению>>

[cols="1,2"]
|===
|*Система*
| УПП / целевая  область транспортной логистики

|*Основное действующее лицо*
| Специалист по логистике

|*Цель*
a| Заказать курьерскую доставку на заказы с признаком прямая гарантия

|*Триггер*
a| По факту наступления cut-off (в регламентированное время) формируем рейсы на основе маршрутов с признаком курьерской доставки

|*Предварительные условия*
a| 

|*Результат*
a| Оформленный заказ в курьерскую службу

|*Постусловия*
|

|*Отклонения*
a| 

|*Допущения*
|


|*Бизнес-правила*
a|  *БПР1:*  Доставка ограничивается весом и габаритами груза  (тяжелые и крупногабаритные посылки) в зависимости от ТК.

*БПР2:* 

|*Не решённые вопросы*
a|. Почему эту работу делает транспортный логист?



|===


.Основной поток событий.

[cols=".<1,.^2,>.4", greed=rows, options=header]
|===
|№ Шага
|Действующее лицо
|Описание шага

|UC1
|Специалист по логистике (*_почему не оператор склада ?_*)
a| *Формирование рейсов*

. Проверить наличие заказов с признаком "Экспресс"
. Выгрузить заказы в рейс и выдать задание на склад

|UC2
|Специалист по логистике
a| *Создание заказов на курьерскую отгрузку в ТК*

. После выдачи заказов на склад, ЗнО становятся доступны к формированию заказа на курьерскую отгрузку
. Автоматически выбирается ТК (на основании подгруженных протоколов согласования цен)
. Через обмены передается информация о грузе и грузополучателе, плановое время доставки
. ТК передает на каждую посылку (один контрагент - одна посылка) трек-номера
. Трек-номера сохраняются в рейсе (с возможностью ручного заполнения и корректировки) + фиксируется плановое время доставки

|UC3
|Специалист по логистике
a| *Заполнить рейс информацией по курьеру*

. В регламентированное время, произвести запрос у ТК о назначенном курьере
. Вносим полученную информацию в рейс

|UC4
|Специалист по логистике
a| *Контроль выполнения доставки*

. получить фактическое время и дату передачи груза грузополучателю от ТК
.. В автоматическом режиме через обмены с ТК
.. Через ручную загрузку реестра доставок
. Проводим сверку и выявление отклонений на основании полученных данных о доставке. (Плановое время и фактическое). На основании отклонений информируем пользователя системы о выявленных отклонениях

|UC5
|Специалист по логистике
a| *Заявка на оплату ТК*

Аналогично *UC3*

|UC6
|Специалист по логистике
a| *Разнесение счетов на оплату ТК*

. Получаем в ЭДО счета
. Проверяем тарифы на корректность
.. Итоговая сумма = вес * тариф ПСЦ
. Заливаем счета в систему  - если ОК, подписываем счет в ЭДО
. Уточнение и корректировка в ТК - если НЕ ОК






|===



=== UC8 Формирование отчетности для ЛИ
<<home, К оглавлению>>

[cols="1,2"]
|===
|*Система*
| УПП / целевая  область транспортной логистики

|*Основное действующее лицо*
|

|*Цель*
a|

|*Триггер*
a| 

|*Предварительные условия*
a| 

|*Результат*
a| 

|*Постусловия*
|

|*Отклонения*
a| 

|*Допущения*
|


|*Бизнес-правила*
a|  *БПР1:*  
*БПР2:* 

|*Не решённые вопросы*
a| . Уточнить какая роль в формировании отчетности лежит на УТЛ - *ЕАЦ*


|===


.Основной поток событий.

[cols=".<1,.^2,>.4", greed=rows, options=header]
|===
|№ Шага
|Действующее лицо
|Описание шага

|UC1
|Специалист по логистике
a| **