@startuml
' Схема отражает передачу полезных объёмов в ИС Magenta

autonumber

title "Передача полезных объёмов"

participant ESB
participant ERP
participant TMS

{start} ESB -> ERP ++:  GET Запрос \nполезных объёмов
ERP -> ESB --: 200 OK

{end} ERP -> ESB++: POST Поставка \nполезных объёмов \n(частями по 1000 записей)
ESB -> ERP --: 200 OK

{start} <-> {end} : По готовности данных в 1С

ESB -> TMS ++: POST Получить SessionID
note over TMS: SessionID действует \nв течении 5 мин
TMS -> ESB -- : XML SessionID
ESB -> TMS : POST XML Полезные объёмы
@enduml