@startuml

    autonumber
    title Алгоритмы обменов
    participant 3PL
    participant 1C
    participant ESB

    =="Существующий вариант"==

    3PL -> 1C: Получаем данные

    =="Целевой вариант"==



@enduml