@startuml


title Порядок работы изменениями

start
    
    repeat

    :Обработать заявку;
    if (Инцидент?) then (Да)
        if (Что требуется?) then (Устранить пследсвия \n инцидента)
        partition "Работа с инцидентом" {
            :Создать задачу на \nустранение последствий \n инцидента;
            
            :Устранить последствия;
            
            :**Закрыть задачу**
            ----
            1. % Выполнения
            2. Статус - **"03.На проверке"**
            3. Фактические даты (начало, конец).;
            :**Закрыть заявку**
            ----
            1.Заполнить решение в в разделе **"решение"**
            2.Отправить ответ пользователю с решением
            3.Изменить статус заявки на **"01.Закрыта"**;

        }
        else (Проанализировать \n проблему)
        partition "Работа с проблемой" {
            :Создать задачу \n на анализ проблемы;
            :На основании заявки \nсоздать проблему;
            :**Провести анализ проблемы**
            ----
            Заполнить:
            1.последствие
            2.причины 
            3.признаки.
            Предложить временное или 
                постоянное решение;
            
            :**Закрыть задачу**
            ----
            1. % Выполнения
            2. Статус - **"03.На проверке"**
            3. Фактические даты (начало, конец).;
            
            :Изменить статус 
            проблемы на 
            **"03.На проверке"**;
        }
        endif
    else (Потребность в изменении)
     partition "Работа с изменением" {
        :Регистрация изменения
        ----
        1.Создание изменения
        2.Предварительная классификация
        3.Получение информации 
        от заказчика (срочность, влияние...);

        :Анализ изменения
        ----
        1.Последствия от изменения
        2.План ввода
        3.План возврата
        4.Критерии приемки
        5.Требуемые простои
        6.Предварительная оценка трудоёмкости
        ;

        if (Трудоёмкость?) then (>2дня)
            
        :Подготовка обоснования RFC
        ----
        1.Выгоды 
        2.BusinessValue
        3.Окупаемость;

        :Согласование CAB
        ----
        1.Состав согласующих
        2.Сроки согласования;
        if (стоимость >500) then (Проектная инициатива)
            :Обоснование на 
            комитете по проектам;
            else (стоимость <500)
        endif    

        else (2дня<)

        
        endif
        :Реализация;
        :Проверка/Тестирование;
        :Закрытие и перенос;

     }
    endif
    
    repeat while (Требуется создание \n доработок?) is (да) not (нет)
end
@enduml