@startuml
'Обсуждение 20/05/2022

autonumber

title "3PL (in) Ответственное хранение (ЛАДА-ИМИДЖ)"
'skinparam BoxPadding 10
'skinparam ParticipantPadding 20
'Схема описывает взаимодействие по процессу ответственного хранения АО ЛадаИмидж'

participant "АО ЛадаИмидж" as 3PL

actor СТП
participant ЭДО as EDO
participant ESB
participant ERP


box "Логистический блок"
participant OMS
participant LST
end box
participant WMS
participant TMS


3PL->ESB: Задание на поставку
activate ESB
    ESB-[#Green]>ERP:ЗнП
        activate ERP #Green
            ERP-[#Green]>ERP:ЗнП
            ERP-[#Green]>ESB:ЗнП
        deactivate ERP
    ESB->OMS: ЗнП
deactivate ESB

activate OMS
    
    OMS->OMS:ЗнП
    OMS <--> LST: ЗнП \nПривязка к рейсу
    'Фактическое прибытие машины, условие: либо акцептуем рейс, либо удаляем ЗнП и ждём выгрузки корректного в случае ошибок. ААА
    LST --> OMS: Рейс акцептован!
    'note over LST: Расписать как будет привязываться рейс
    'Нарисовать привязку к рейсу как в отгрузке. - КЕА
deactivate OMS

|||

OMS->ESB:ЗнП
activate ESB
    ESB->WMS: ЗнП
deactivate ESB

WMS->ESB:Подтверждение ЗнП
activate ESB
    ESB->OMS:Подтверждение ЗнП
deactivate ESB
    activate OMS
        OMS ->OMS:Статус ЗнП
        OMS ->ESB:Подтверждение ЗнП
        activate ESB
    deactivate OMS
        ESB->ERP:Подтверждение ЗнП
            
        deactivate ESB    
            activate ERP
        
                ERP->ERP: МХ1
                group #Lightgreen Передача MX1 [LoadDelivery] 
                                      
                    ERP->3PL:МХ1
                    activate 3PL
                         3PL->3PL:MX1
                        
                        3PL->ERP:OK
                    deactivate 3PL
                else #White ЭДО
                    {Начало} ERP->EDO:MX1
                    
             deactivate ERP
                    ...Неопределенное время...       
                    EDO->3PL:MX1
                    3PL->EDO:Подписанный MX1
                    ...Неопределенное время...
                    {Конец} EDO->ERP:Подписанный MX1
                    {Начало} <-> {Конец}: Неопределённое время!
                end
            
@enduml