@startuml

autonumber

title "ABOM Транзитный заказ без заезда на склад"
'skinparam BoxPadding 10
'skinparam ParticipantPadding 20
'Схема описывает взаимодействие по процессу ответственного хранения АО ЛадаИмидж'

participant "ABOM" as B2B
actor СТП
participant ЭДО as EDO
participant ESB
participant ERP

box "Логистический блок"
participant OMS
participant LST
end box
participant WMS

B2B -> ESB : Заказ покупателя \n(транзитный без заезда)
activate ESB
ESB -> ERP : Заказ покупателя \n(транзитный без заезда)
deactivate ESB

activate ERP
ERP -> ERP: Заказ покупателя
ERP -> ERP: Заказ поставщику
deactivate ERP

!include Подпроцессы\ПТиУ через ЭДО.pu


|||
B2B -> ESB: Отгрузка поставщика
activate ESB
ESB -> ERP :  Отгрузка поставщика

deactivate ESB
activate ERP 

'входящий и исходящий ЭДО
'

ERP -> ERP : Поступление
ERP -> ERP : Сопоставление \nПоступления и ЭДО
ERP -> ERP : Реализация
deactivate ERP

|||

!include Подпроцессы\Реализация через ЭДО.pu
|||
ERP -> ESB: РТиУ

activate ESB
ESB -> B2B : Отгрузка на портале
deactivate ESB
|||
!include Подпроцессы\Подтверждение ПТиУ через ЭДО.pu


@enduml