@startuml
'Обсуждение 18/05/2022
autonumber

title "ABOM Продажа из собственного ресурса"
'skinparam BoxPadding 10
'skinparam ParticipantPadding 20
'Схема описывает взаимодействие по процессу ответственного хранения АО ЛадаИмидж'

participant "ABOM" as B2B
actor СТП
participant ЭДО as EDO
participant ESB
participant ERP

box "Логистический блок"
participant OMS
participant LST
end box
participant WMS

B2B -> ESB : Заказ покупателя (простой)
activate ESB
ESB -> ERP : Заказ покупателя (простой)
deactivate ESB

activate ERP
ERP -> ERP: Заказ покупателя
ERP -> ERP: Резервирование

ERP -->ESB : Отказ по тому чего нет
activate ESB
ESB --> B2B : Отказ по тому чего нет
deactivate ESB

ERP -[#Green]> ERP : ЗнО
activate ERP #LightGreen
ERP -> ESB: "Отгрузить!"/ЗнО

deactivate ERP
deactivate ERP
activate ESB
ESB -> OMS: "Отгрузить!"/ЗнО
deactivate ESB
activate OMS

OMS -> OMS: ЗнО
deactivate OMS

!include Подпроцессы\Выдача ЗнО.pu
!include Подпроцессы\ФТ8 Приоритезация.pu

group Отбор товара
activate WMS


WMS -> ESB: Товар отобран!
activate ESB
ESB -> OMS: Товар отобран!
deactivate ESB

note right: Новый функционал, \nпередача \nдополнительного статуса

end

OMS -[#Red]-> LST: Команда складу отгрузить !


!include Подпроцессы\ФТ9 Приоритезация.pu

!include Подпроцессы\Товар в ТС.pu

!include Подпроцессы\РТиУ.pu
ERP -> ESB: РТиУ
activate ESB
ESB -> B2B : Отгрузка на портале
deactivate ESB

!include Подпроцессы\Готовность к оформлению документов.pu

!include Подпроцессы\Отгрузка ТС.pu

@enduml