@startuml

actor Поклажедатель as pd <<ЛадаИмидж>>
actor :Пользователь: as po
agent ERP as erp
agent WMS as wms
agent TMS as tms
storage "LST/OMS" as lst

po --> lst : Рейс
pd --> lst : ЗнО\nЗнП
erp --> lst : ЗнО\nЗнП\nНоменклатура?\nКонтрагенты?
tms --> lst : Подтв. рейса\nМаршрут
lst --> wms : ЗнО\nЗнП
lst --> tms : ЗнО
wms --> lst : подтв.ЗнО\nподтв.ЗнП

note "1.Данная схема целевая. \n 2.Отказ от посылок в ERP \n 3.Что будет, если контрагентов двое? " as n1
note left of po : "Оператор склада"
note "Создание маршрутов Создаем ЗнО\nСоздаем ОЧЕРЕДНОЙ рейс\nНаполнить ТЕКУЩИЙ рейс ЗнО\nСоздание рейса разгрузки\nСоздаем ЗнП\nНаполнить рейс разгрузки ЗнП" as n2

lst .. n1
n1 .. wms
lst .. n2

@enduml
