@startuml

title "Схема существующих бэкапов"

component [1C] as upp
component [ЭДО + \nКаталоги \nподразделений] as edo
component [Файловый сервер] as fserver
component [INFOR]
component [Фото-сервер] as photo

component [Жесткие диски \n отдельное хранение] as hd


component [бэкапы ABOM] as ABOM

node РИТ <<Бэкапов не производится!>> {
    component [1C РИТ] as rit
    
}

cloud "1-й сервер бэкапов - ул.Озерная, д.14, к.1" <<Глубина хранения до 5-ти копий>> {

    folder folder1 [
        рег. задание 1
        ====
        Все бэкапы 1С

    ]

    folder folder2 [
        рег. задание 2
        ====
        Каталоги с технической
        и рабочей информацией
    ]
      folder folder3 [
        рег. задание 3
        ====
        INFOR-бэкапы 
        по всем площадкам
    ]

      folder folder4 [
        рег. задание 4
        ====
        Файловый 
        документооборот 
        компании
        
    ]

    

}

upp --> folder1: БД


edo --> folder2: Системные файлы


INFOR --> folder3: Системные \nфайлы INFOR

fserver --> folder4 : файлы

folder1 --> hd : "ежеквартальное \nсохранение"


cloud "2-й сервер бэкапов - рег.склад в г.Тверь" <<Глубина хранения до 10-ти копий>>{

 folder folder5 [
        рег. задание 1
        ====
        Все бэкапы 1С

    ]

    folder folder6 [
        рег. задание 2
        ====
        Каталоги с технической
        и рабочей информацией
    ]
      folder folder7 [
        рег. задание 3
        ====
        INFOR-бэкапы 
        по всем площадкам
    ]

      folder folder8 [
        рег. задание 4
        ====
        Файловый 
        документооборот 
        компании
        
    ]

    folder folder9 [

        Хранилище бэкапов
        ABOM
    ]

}

photo --> folder3: фото \nтоваров

folder1 --> folder5
folder2 --> folder6
folder3 --> folder7
folder4 --> folder8

ABOM --> folder9

@enduml