@startuml

group #LightGreen LoadShipment [Реализуется для УПП]
'Описание передачи МХ3 по web-обменам
        activate 3PL
        ERP -> 3PL :МХ3
        3PL -> 3PL :МХ3 / Реализация 
        3PL --> ERP :OK
        end

@enduml