@startuml

'Последовательность обмена поступление через ЭДО

      group #LightGoldenRodYellow РТиУ через ЭДО
        3PL -> EDO: Подписанный РТиУ
        EDO -> ERP : Подписанный РТиУ
       else Ошибка
       EDO -> ERP: Не успешно
       note OVER ESB #red: "Сообщение в СТП"
       end


@enduml