@startuml

'Последовательность обмена поступление через ЭДО

      group #LightGoldenRodYellow РТиУ через ЭДО поставщика
         -> EDO: Подписанный РТиУ поставщика
       ' EDO -> ERP : Подписанный РТиУ поставщика
       
       end


@enduml