@startuml
group Отбор товара
activate WMS


WMS -> ESB: Товар упакован!
activate ESB
ESB -> OMS: Товар упакован!
deactivate ESB

note right: Новый функционал, \nпередача \nдополнительного статуса

' Вариант ответа БДРТ
OMS -> ESB: МХ3
'deactivate OMS
activate ESB
ESB -> ERP: МХ3
deactivate ESB
activate ERP


ERP -> ERP : МХ3 

end

@enduml