@startuml

           group Создание ЗнО
            ESB -[#Green]> ERP: Создание ЗнО
            activate  ERP #Green
            'Разобраться с активейтами!!!!!

            

            ERP -[#Green]> ERP: Создание ЗнО
            ERP -[#Green]> ESB: Создание ЗнО

            deactivate ERP
            ESB ->OMS :Создание ЗнО
        deactivate ESB
            activate OMS
            OMS -> OMS : ЗнО
            deactivate OMS
        end

@enduml