@startuml

group #LightGoldenRodYellow ФТ9 Плановое время отгрузки 
    else [Попадают не отобранные ЗнО]
    OMS -> LST : Привязка к \nочередному рейсу (ФТ8)
    activate LST
    LST --> OMS : Рейс привязан 
    deactivate LST

    OMS -> ESB : Передать новый рейс
    activate ESB
    ESB -> WMS : Передать новый рейс
    deactivate ESB

    
else [Случай для ЕКТ]
note over LST: "как будет реализовываться передача информации по рейсу ?"

else [Случай для НСБ]
note over LST: "как будет реализовываться передача информации по рейсу ?"

end

@enduml