@startuml

title Диаграмма состояний обозначения

state Старт <<start>>
state Конец <<end>>
state Выбор <<choice>>

note left of Старт: "Стартовое событие"


Старт --> Состояние1
[*] --> Состояние1

Состояние1 : Список внутренних \nдействий в \nданном состоянии

Состояние2 : Действие 1
Состояние2 : Действие 2

state fork_state <<fork>>
Состояние1 --> fork_state
fork_state --> Состояние2
fork_state --> Состояние3

state join_state <<join>>

Состояние1 --> join_state : Событие1

Состояние1 --> join_state : Событие2

join_state --> Состояние2

state СоставноеСостояние {
    state ТочкаПодключения <<entrypoint>>
    [*] --> Состояние4
    state ExitPoint <<exitpoint>>
}

Состояние3 --> ТочкаПодключения

Состояние4 --> Состояние2
ExitPoint -u-> Состояние2

state "Длинное название \nсостояния" as st5
Состояние2 --> st5

st5 --> st5 : Новые данные

st5 --> Выбор

Выбор --> Конец

@enduml