@startuml

'Обсуждение 18/05/2022
autonumber

title "3PL Отвественное хранение (Лада-Имидж) (Out)"
'skinparam BoxPadding 10
'skinparam ParticipantPadding 20
'Схема описывает взаимодействие по процессу ответственного хранения АО ЛадаИмидж'

participant "АО ЛадаИмидж/БДРТ" as 3PL
actor СТП
participant ЭДО as EDO
participant ESB
participant ERP

box "Логистический блок"
participant OMS
participant LST
end box
participant WMS
participant TMS

'== 3PL Ответственное хранение (ЛАДА-ИМИДЖ / БДРТ) ==


3PL ->ESB: Задание на отгрузку

!include Подпроцессы\Создание ЗнО.pu
activate OMS



!include  Подпроцессы\Выдача ЗнО.pu
deactivate ESB

'ЗнО блок отработки
|||
group Приоритезация

!include  Подпроцессы\ФТ8 Приоритезация.pu

note OVER WMS #red:"Добавить в процесс\nприоритезацию"
note OVER WMS #red:"Описать порядок \nпривязки к рейсу"

!include  Подпроцессы\Отбор товара.pu

!include  Подпроцессы\LoadShipment.pu



note over 3PL #red : "Ждём подписания от ЛИ \nили грузим не дожидаясь ?"

!include  Подпроцессы\ЭДО МХ3.pu


deactivate 3PL
!include  Подпроцессы\Готовность к оформлению документов.pu
!include  Подпроцессы\Готовность к отгрузке.pu

!include  Подпроцессы\ФТ9 Приоритезация.pu

'В будущем МХ3 будем передавать через ЭДО надо добавить на схему'
'Надо добавить расшифровку привязки к рейсу на схему'

end

'ERP -> OMS : Готов к отгрузке!
'OMS -[#Red]-> WMS : Команда складу \nотгрузить!
!include  Подпроцессы\Товар в ТС.pu
'----------------------------------------------------------------

!include  Подпроцессы\Отгрузка ТС.pu



@enduml