@startuml
'Обсуждение 20/05/2022
autonumber

title "ABOM перемещение КД с последующей продажей(окончание)"
'skinparam BoxPadding 10
'skinparam ParticipantPadding 20
'Схема описывает взаимодействие по процессу ответственного хранения АО ЛадаИмидж'

participant "ABOM" as B2B
actor СТП
participant ЭДО as EDO
participant ESB
participant ERP

box "Логистический блок"
participant OMS
participant LST
end box
participant WMS


activate OMS

OMS -> OMS: ЗнО
OMS -> OMS: ЗнП

deactivate OMS

note OVER OMS #Red : "Нужно отрисовать совместно с Альбиной! "
'Нужно отрисовать приёмку по КД + привязку к рейсу поступления

!include Подпроцессы\Выдача ЗнО.pu
!include Подпроцессы\ФТ8 Приоритезация.pu

group Отбор товара
activate WMS


WMS -> ESB: Товар упакован!
activate ESB
ESB -> OMS: Товар упакован!
deactivate ESB

note right: Новый функционал, \nпередача \nдополнительного статуса

end

OMS -[#Red]-> LST: Команда складу отгрузить !


!include Подпроцессы\ФТ9 Приоритезация.pu

!include Подпроцессы\Товар в ТС.pu

!include Подпроцессы\РТиУ.pu
ERP -> ESB: РТиУ
activate ESB
ESB -> B2B : Отгрузка на портале
deactivate ESB

!include Подпроцессы\Готовность к оформлению документов.pu

!include Подпроцессы\Отгрузка ТС.pu

@enduml