@startuml

left to right direction

title "UseCase LST"
actor "Оператор склада" as OP
actor "Специалист по планированию" as PL
'actor "Специалист по работе с отклонениями" as SO
'actor "Планирующий работу по претензиям" as PP

'actor Поставщик as SP
'actor Покупатель as CU



rectangle "LST/ АРМ оператора"  {
    (Обмен данными с\n поклажедателями)
    OP --> (Коммерческий акт)
    OP --> (Связывание рейса с ЗнО)
    OP --> (Запуск приёмки в работу)
    OP --> (Подтверждение корректности \nсверки документов поставки)
    OP --> (Зафиксированы контрольные \nсобытия)
    OP --> (Комментарии по возникшим \nотклонениям)
    OP --> (Товаро-сопроводительные \nдокументы)
    OP --> (Оперативная отчетность)
    OP --> (Документы для \nпоклажедателей)
    OP --> (Резервирование свободного\nокна отгрузки/разгрузки)
    
    PL --> (Расписание отгрузки/разгрузки )
    PL --> (План загрузки склада)
    PL --> (Уточненный план)
    PL --> (Записи в справочниках)




}