@startuml

left to right direction

title Варианты использования функционала транспортной логистики

actor "Специалист \nпо логистике" as LG
:ERP:




rectangle "TMS Magenta" {
    usecase "Планирование а/м"  #PaleGreen
    usecase "Квотирование рейсов"  #PaleGreen
    usecase "Контроль прибытия а/м\n на погрузку/выгрузку"  #PaleGreen
    usecase "Логистический стандарт"  #PaleGreen

    LG --> (Планирование а/м)
    (Планирование а/м) --> (Заказ а/м)
    'LG --> (Заказ а/м)
    LG --> (Формирование графика перевозчика)
    (Формирование графика перевозчика) --> (Планирование а/м)
    (Реестр рейсов: маршрут, грузополучатели, \nтип а/м, ставки и т.д.\) --> ERP                                                                                                
    (Формирование графика перевозчика) <--(Логистический стандарт)
    '(Формирование графика перевозчика) <-- (Обмен заявками, получение\n данных и доверенностей)
    (Реестр рейсов: маршрут, грузополучатели, \nтип а/м, ставки и т.д.\) <-- (Обмен заявками, получение\n данных и доверенностей)
    'ERP -->(Обмен заявками, получение\n данных и доверенностей)
    (Заказ а/м)-->(Обмен заявками, получение\n данных и доверенностей)
    LG --> (Квотирование рейсов)
    LG --> (Контроль прибытия а/м\n на погрузку/выгрузку)
    (Контроль прибытия а/м\n на погрузку/выгрузку) <-- (Трекинг)
    (Контроль прибытия а/м\n на погрузку/выгрузку)  --> (KPI перевозчика)
    (Квотирование рейсов) --> (Формирование графика перевозчика)
    '(Заказ а/м) --> (Реестр рейсов: маршрут, грузополучатели, \nтип а/м, ставки и т.д.\)
    'LG --> (Обмен заявками, получение\n данных и доверенностей)
    'LG --> (KPI перевозчика)
    LG --> (Логистический стандарт) 
    (Логистический стандарт) --> (Планирование а/м)
    'LG --> (Трекинг)
    'LG --> (Реестр рейсов: маршрут, грузополучатели, \nтип а/м, ставки и т.д.\)

}

rectangle "ERP ЛОГИСТИКА" {
    usecase "Формирование ПСЦ"  #PaleGreen
    usecase "ВЭД, оформление документов"  #Yellow
    usecase "Выгрузка и оформление\n экспрессотправлений"  #Yellow
    usecase "Разнесение счетов и актов"  #Yellow
    usecase "Подготовка и оформление \n заявок на оплату"  #Yellow
    usecase "Претензионная работа"  #Yellow
    usecase "Формирование отчетности \nпо транспортным затратам"  #Yellow
    usecase "Передача данных по рейсам \n в ЛИ отчетность"  #Yellow
    

    LG --> (ВЭД, оформление документов)
    LG --> (Выгрузка и оформление\n экспрессотправлений)
    LG --> (Разнесение счетов и актов)
    LG --> (Подготовка и оформление \n заявок на оплату)
    LG --> (Претензионная работа)
    LG --> (Формирование ПСЦ)
    LG --> (Формирование отчетности \nпо транспортным затратам)
    (Формирование отчетности \nпо транспортным затратам) --> (Передача данных по рейсам \n в ЛИ отчетность)

    'LG --> (Передача данных по рейсам \n в ЛИ отчетность)


}


@enduml